"""Canvas chart item rendering backed by Matplotlib."""

import math
import textwrap
from collections import defaultdict, deque
from statistics import mean, median

import matplotlib
matplotlib.use("Agg")
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.figure import Figure
from matplotlib.patches import FancyBboxPatch, PathPatch
from matplotlib.path import Path as MplPath

from PySide6.QtWidgets import QGraphicsItem
from PySide6.QtCore import Qt, QRectF, QPointF, QSizeF, QTimer
from PySide6.QtGui import QPainter, QColor, QBrush, QPen, QFont, QPainterPath, QImage, QLinearGradient

from graphite_config import get_current_palette, get_graph_node_colors


class ChartItem(QGraphicsItem):
    """
    A QGraphicsItem that renders a data chart using Matplotlib.
    It takes a structured data dictionary and generates a chart image, which is
    then displayed on the canvas.
    """

    PADDING = 20
    HEADER_HEIGHT = 40
    MIN_WIDTH = 440
    MIN_HEIGHT = 320
    RESIZE_DEBOUNCE_MS = 90

    def __init__(self, data, pos, parent=None, parent_content_node=None):
        """
        Initializes the ChartItem.

        Args:
            data (dict): The structured data for the chart, as generated by ChartDataAgent.
            pos (QPointF): The initial position of the chart on the scene.
            parent (QGraphicsItem, optional): The parent item. Defaults to None.
        """
        super().__init__(parent)
        self.setPos(pos)
        self.data = data
        self.title = data.get("title", "Chart")
        self.parent_content_node = parent_content_node
        self.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIsMovable)
        self.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIsSelectable)
        self.setFlag(QGraphicsItem.GraphicsItemFlag.ItemSendsGeometryChanges)
        self.setAcceptHoverEvents(True)

        self.width = 680
        self.height = 500
        self.hovered = False
        self.resize_handle_hovered = False
        self.resizing = False
        self.chart_image = QImage()

        self.figure = Figure(figsize=(6, 4), dpi=160)
        self.canvas = FigureCanvasAgg(self.figure)

        self.render_timer = QTimer()
        self.render_timer.setSingleShot(True)
        self.render_timer.setInterval(self.RESIZE_DEBOUNCE_MS)
        self.render_timer.timeout.connect(self.generate_chart)

        self.generate_chart()

    def _chart_type(self):
        return str(self.data.get("type", "chart")).strip().lower()

    def _chart_rect(self):
        top = self.HEADER_HEIGHT + 16
        height = max(140, self.height - top - self.PADDING)
        return QRectF(
            self.PADDING,
            top,
            max(200, self.width - (self.PADDING * 2)),
            height,
        )

    def _badge_text(self):
        chart_type = self._chart_type()
        return chart_type.replace("_", " ").title() if chart_type else "Chart"

    def _header_accent(self, palette):
        return get_graph_node_colors()["header_start"]

    def _device_pixel_ratio(self):
        if self.scene() and self.scene().views():
            view = self.scene().views()[0]
            if hasattr(view, "devicePixelRatioF"):
                return max(1.0, float(view.devicePixelRatioF()))
        return 1.5

    def _set_figure_geometry(self):
        chart_rect = self._chart_rect()
        pixel_ratio = self._device_pixel_ratio()
        target_width = max(640, int(chart_rect.width() * pixel_ratio))
        target_height = max(420, int(chart_rect.height() * pixel_ratio))
        dpi = max(140, int(120 * pixel_ratio))
        self.figure.set_dpi(dpi)
        self.figure.set_size_inches(target_width / dpi, target_height / dpi, forward=True)

    @staticmethod
    def _with_alpha(color, alpha):
        new_color = QColor(color)
        new_color.setAlpha(alpha)
        return new_color

    @staticmethod
    def _blend_colors(color_a, color_b, ratio):
        ratio = max(0.0, min(1.0, ratio))
        inv = 1.0 - ratio
        return QColor(
            int((color_a.red() * inv) + (color_b.red() * ratio)),
            int((color_a.green() * inv) + (color_b.green() * ratio)),
            int((color_a.blue() * inv) + (color_b.blue() * ratio)),
        )

    @staticmethod
    def _mpl_rgba(color, alpha=1.0):
        return (color.redF(), color.greenF(), color.blueF(), alpha)

    def _build_theme(self, palette):
        surface = QColor("#171b21")
        panel = QColor("#11161d")
        border = QColor("#414855")
        text = QColor("#f5f7fb")
        muted = QColor("#9aa6b8")
        grid = QColor("#8f9bb0")
        primary = QColor(palette.AI_NODE)
        secondary = QColor(palette.USER_NODE)
        selection = QColor(palette.SELECTION)
        accent = self._blend_colors(primary, secondary, 0.55)
        tertiary = self._blend_colors(primary, selection, 0.50)
        slate = QColor("#6f8aa6")

        cycle = [
            primary,
            secondary,
            accent,
            tertiary,
            self._blend_colors(primary, secondary, 0.35),
            self._blend_colors(secondary, selection, 0.40),
            primary.lighter(130),
            slate,
        ]

        return {
            "surface": surface,
            "panel": panel,
            "border": border,
            "text": text,
            "muted": muted,
            "grid": grid,
            "primary": primary,
            "secondary": secondary,
            "accent": accent,
            "selection": selection,
            "cycle": cycle,
        }

    @staticmethod
    def _coerce_number(value):
        try:
            number = float(value)
        except (TypeError, ValueError):
            return None
        if not math.isfinite(number):
            return None
        return number

    @staticmethod
    def _format_value(value):
        if abs(value) >= 1000:
            return f"{value:,.0f}"
        if abs(value - round(value)) < 0.001:
            return f"{value:,.0f}"
        return f"{value:,.2f}".rstrip("0").rstrip(".")

    def _wrap_label(self, text, width=14, max_lines=2):
        clean_text = " ".join(str(text).split())
        if not clean_text:
            return ""
        lines = textwrap.wrap(
            clean_text,
            width=width,
            break_long_words=False,
            break_on_hyphens=False,
        )
        if not lines:
            return clean_text
        if len(lines) > max_lines:
            kept = lines[: max_lines - 1]
            remainder = " ".join(lines[max_lines - 1 :])
            kept.append(textwrap.shorten(remainder, width=width, placeholder="..."))
            lines = kept
        return "\n".join(lines)

    def _sanitize_chart_data(self):
        chart_type = self._chart_type()
        cleaned = {
            "type": chart_type,
            "title": str(self.data.get("title", "Chart")).strip() or "Chart",
        }

        if chart_type in {"bar", "line", "pie"}:
            labels = []
            values = []
            for raw_label, raw_value in zip(self.data.get("labels", []), self.data.get("values", [])):
                number = self._coerce_number(raw_value)
                label = "" if raw_label is None else str(raw_label).strip()
                if not label or number is None:
                    continue
                if chart_type == "pie" and number <= 0:
                    continue
                labels.append(label)
                values.append(number)

            if not labels or not values:
                raise ValueError("The chart data does not contain enough valid labeled values.")

            cleaned["labels"] = labels
            cleaned["values"] = values
            cleaned["xAxis"] = str(self.data.get("xAxis", "")).strip()
            cleaned["yAxis"] = str(self.data.get("yAxis", "")).strip()
            return cleaned

        if chart_type == "histogram":
            values = [
                number
                for number in (self._coerce_number(value) for value in self.data.get("values", []))
                if number is not None
            ]
            if len(values) < 2:
                raise ValueError("Histogram charts need at least two numeric values.")
            bins = self.data.get("bins", 10)
            bins = int(bins) if isinstance(bins, (int, float)) else 10
            cleaned["values"] = values
            cleaned["bins"] = max(3, min(24, bins, len(values)))
            cleaned["xAxis"] = str(self.data.get("xAxis", "")).strip()
            cleaned["yAxis"] = str(self.data.get("yAxis", "Frequency")).strip() or "Frequency"
            return cleaned

        if chart_type == "sankey":
            flows = []
            raw_flows = self.data.get("flows", [])
            if not raw_flows and isinstance(self.data.get("data"), dict):
                nodes = self.data["data"].get("nodes", [])
                links = self.data["data"].get("links", [])
                raw_flows = []
                for link in links:
                    source_idx = link.get("source")
                    target_idx = link.get("target")
                    if not isinstance(source_idx, int) or not isinstance(target_idx, int):
                        continue
                    if source_idx >= len(nodes) or target_idx >= len(nodes):
                        continue
                    raw_flows.append(
                        {
                            "source": nodes[source_idx].get("name", f"Node {source_idx}"),
                            "target": nodes[target_idx].get("name", f"Node {target_idx}"),
                            "value": link.get("value"),
                        }
                    )

            for flow in raw_flows:
                source = str(flow.get("source", "")).strip()
                target = str(flow.get("target", "")).strip()
                value = self._coerce_number(flow.get("value"))
                if not source or not target or value is None or value <= 0:
                    continue
                flows.append({"source": source, "target": target, "value": value})

            if not flows:
                raise ValueError("Sankey charts need at least one valid flow.")

            cleaned["flows"] = flows
            return cleaned

        raise ValueError(f"Unsupported chart type: {chart_type or 'unknown'}")

    def _prepare_standard_axes(self, ax, theme, x_label="", y_label="", x_grid=False, y_grid=True):
        ax.set_facecolor(theme["surface"].name())
        ax.tick_params(colors=theme["muted"].name(), labelsize=8)
        for side in ax.spines.values():
            side.set_color(theme["border"].name())
            side.set_linewidth(1.0)
        if y_grid:
            ax.grid(axis="y", color=self._mpl_rgba(theme["grid"], 0.18), linewidth=0.8, linestyle="--")
        if x_grid:
            ax.grid(axis="x", color=self._mpl_rgba(theme["grid"], 0.18), linewidth=0.8, linestyle="--")
        ax.set_axisbelow(True)
        if x_label:
            ax.set_xlabel(x_label, fontsize=9, color=theme["muted"].name(), labelpad=10)
        if y_label:
            ax.set_ylabel(y_label, fontsize=9, color=theme["muted"].name(), labelpad=8)

    def _render_bar_chart(self, ax, chart_data, theme):
        values = chart_data["values"]
        labels = chart_data["labels"]
        positions = list(range(len(values)))
        colors = [theme["cycle"][index % len(theme["cycle"])].name() for index in range(len(values))]

        bars = ax.bar(
            positions,
            values,
            width=0.62,
            color=colors,
            edgecolor=self._with_alpha(theme["text"], 40).name(),
            linewidth=0.8,
            zorder=3,
        )
        self._prepare_standard_axes(ax, theme, chart_data["xAxis"], chart_data["yAxis"], y_grid=True)
        ax.set_xticks(positions)
        ax.set_xticklabels([self._wrap_label(label, 12, 2) for label in labels])
        ax.margins(x=0.04)

        min_value = min(values)
        max_value = max(values)
        if min_value >= 0:
            ax.set_ylim(0, max_value * 1.18 if max_value else 1)
        else:
            buffer = (max_value - min_value) * 0.12 or 1
            ax.set_ylim(min_value - buffer, max_value + buffer)
            ax.axhline(0, color=self._with_alpha(theme["text"], 90).name(), linewidth=1.0)

        if len(values) <= 10:
            for bar, value in zip(bars, values):
                va = "bottom" if value >= 0 else "top"
                offset = 4 if value >= 0 else -4
                ax.annotate(
                    self._format_value(value),
                    (bar.get_x() + (bar.get_width() / 2), value),
                    textcoords="offset points",
                    xytext=(0, offset),
                    ha="center",
                    va=va,
                    color=theme["text"].name(),
                    fontsize=8,
                )
        return True

    def _render_line_chart(self, ax, chart_data, theme):
        values = chart_data["values"]
        labels = chart_data["labels"]
        positions = list(range(len(values)))
        baseline = min(0, min(values))

        self._prepare_standard_axes(ax, theme, chart_data["xAxis"], chart_data["yAxis"], y_grid=True)
        ax.plot(
            positions,
            values,
            color=theme["primary"].name(),
            linewidth=2.8,
            marker="o",
            markersize=6,
            markerfacecolor=theme["surface"].name(),
            markeredgewidth=1.6,
            markeredgecolor=theme["text"].name(),
            zorder=4,
        )
        ax.fill_between(
            positions,
            values,
            baseline,
            color=self._mpl_rgba(theme["primary"], 0.15),
            zorder=2,
        )
        ax.set_xticks(positions)
        ax.set_xticklabels([self._wrap_label(label, 12, 2) for label in labels])
        ax.margins(x=0.04)

        value_span = max(values) - min(values)
        buffer = (value_span * 0.18) or max(abs(max(values)), 1) * 0.18 or 1
        ax.set_ylim(min(values) - buffer, max(values) + buffer)
        if len(values) <= 12:
            for x_pos, value in zip(positions, values):
                ax.annotate(
                    self._format_value(value),
                    (x_pos, value),
                    textcoords="offset points",
                    xytext=(0, 8),
                    ha="center",
                    color=theme["text"].name(),
                    fontsize=8,
                )
        return True

    def _render_pie_chart(self, ax, chart_data, theme):
        values = chart_data["values"]
        labels = chart_data["labels"]
        colors = [theme["cycle"][index % len(theme["cycle"])] for index in range(len(values))]
        total = sum(values)

        self.figure.subplots_adjust(left=0.06, right=0.78, top=0.92, bottom=0.08)
        wedges, _ = ax.pie(
            values,
            startangle=90,
            counterclock=False,
            labels=None,
            colors=[color.name() for color in colors],
            wedgeprops={"width": 0.38, "edgecolor": theme["surface"].name(), "linewidth": 2},
        )

        ax.text(
            0,
            0.05,
            self._format_value(total),
            ha="center",
            va="center",
            color=theme["text"].name(),
            fontsize=16,
            fontweight="bold",
        )
        ax.text(
            0,
            -0.16,
            "Total",
            ha="center",
            va="center",
            color=theme["muted"].name(),
            fontsize=9,
        )

        legend_labels = []
        for label, value in zip(labels, values):
            percentage = (value / total) * 100 if total else 0
            wrapped = self._wrap_label(label, 20, 2).replace("\n", " ")
            legend_labels.append(f"{wrapped}  {percentage:.1f}%")

        legend = ax.legend(
            wedges,
            legend_labels,
            loc="center left",
            bbox_to_anchor=(0.98, 0.5),
            frameon=False,
            fontsize=8,
            handlelength=1.2,
            handletextpad=0.6,
        )
        for text in legend.get_texts():
            text.set_color(theme["text"].name())

        ax.set_aspect("equal")
        ax.set_facecolor(theme["surface"].name())
        return False

    def _render_histogram(self, ax, chart_data, theme):
        values = chart_data["values"]
        bins = chart_data["bins"]

        counts, _, patches = ax.hist(
            values,
            bins=bins,
            linewidth=1.0,
            edgecolor=self._with_alpha(theme["text"], 60).name(),
            zorder=3,
        )
        for index, patch in enumerate(patches):
            color = theme["cycle"][index % len(theme["cycle"])]
            patch.set_facecolor(color.name())
            patch.set_alpha(0.82)

        avg = mean(values)
        med = median(values)
        self._prepare_standard_axes(ax, theme, chart_data["xAxis"], chart_data["yAxis"], y_grid=True)
        ax.axvline(
            avg,
            color=theme["primary"].name(),
            linewidth=1.6,
            linestyle="--",
            label=f"Mean {self._format_value(avg)}",
            zorder=4,
        )
        ax.axvline(
            med,
            color=theme["secondary"].name(),
            linewidth=1.6,
            linestyle="-.",
            label=f"Median {self._format_value(med)}",
            zorder=4,
        )
        legend = ax.legend(frameon=False, fontsize=8, loc="upper right")
        for text in legend.get_texts():
            text.set_color(theme["muted"].name())
        ax.set_ylim(0, (max(counts) * 1.18) if len(counts) and max(counts) else 1)
        return True

    def _render_sankey_chart(self, ax, chart_data, theme):
        flows = chart_data["flows"]
        incoming = defaultdict(list)
        outgoing = defaultdict(list)
        indegree = defaultdict(int)
        nodes = set()

        for flow in flows:
            source = flow["source"]
            target = flow["target"]
            nodes.add(source)
            nodes.add(target)
            outgoing[source].append(flow)
            incoming[target].append(flow)
            indegree[target] += 1
            indegree.setdefault(source, 0)

        levels = {}
        queue = deque(sorted(node for node in nodes if indegree[node] == 0))
        for node in queue:
            levels[node] = 0

        while queue:
            node = queue.popleft()
            for flow in outgoing[node]:
                target = flow["target"]
                levels[target] = max(levels.get(target, 0), levels[node] + 1)
                indegree[target] -= 1
                if indegree[target] == 0:
                    queue.append(target)

        for node in nodes:
            if node not in levels:
                levels[node] = max((levels.get(flow["source"], 0) + 1 for flow in incoming[node]), default=0)

        column_map = defaultdict(list)
        node_weights = {}
        for node in nodes:
            node_weights[node] = max(
                sum(flow["value"] for flow in outgoing[node]),
                sum(flow["value"] for flow in incoming[node]),
                1.0,
            )
            column_map[levels[node]].append(node)

        column_gap = 0.03
        chart_height = 0.82
        available_columns = max(column_map.keys()) + 1 if column_map else 1
        global_scale = None
        for column_nodes in column_map.values():
            total_weight = sum(node_weights[node] for node in column_nodes)
            available_height = chart_height - (column_gap * max(0, len(column_nodes) - 1))
            if total_weight <= 0 or available_height <= 0:
                continue
            column_scale = available_height / total_weight
            global_scale = column_scale if global_scale is None else min(global_scale, column_scale)
        scale = global_scale or 0.04

        x_start = 0.08
        x_end = 0.92
        step = (x_end - x_start) / max(1, available_columns - 1)
        node_width = min(0.05, step * 0.28)
        node_layout = {}

        for level in sorted(column_map.keys()):
            column_nodes = sorted(column_map[level], key=lambda node: (-node_weights[node], node.lower()))
            total_height = sum(node_weights[node] * scale for node in column_nodes)
            total_height += column_gap * max(0, len(column_nodes) - 1)
            current_y = 0.5 - (total_height / 2)
            for node in column_nodes:
                height = node_weights[node] * scale
                node_layout[node] = {
                    "x": x_start + (level * step),
                    "y": current_y,
                    "width": node_width,
                    "height": height,
                    "level": level,
                }
                current_y += height + column_gap

        outgoing_cursor = {node: layout["y"] for node, layout in node_layout.items()}
        incoming_cursor = {node: layout["y"] for node, layout in node_layout.items()}
        max_level = max((layout["level"] for layout in node_layout.values()), default=0)

        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.axis("off")
        ax.set_facecolor(theme["surface"].name())
        self.figure.subplots_adjust(left=0.02, right=0.98, top=0.94, bottom=0.05)

        sorted_flows = sorted(
            flows,
            key=lambda flow: (
                node_layout[flow["source"]]["level"],
                node_layout[flow["source"]]["y"],
                node_layout[flow["target"]]["y"],
            ),
        )

        for flow in sorted_flows:
            source_layout = node_layout[flow["source"]]
            target_layout = node_layout[flow["target"]]
            thickness = max(flow["value"] * scale, 0.008)

            start_y0 = outgoing_cursor[flow["source"]]
            start_y1 = start_y0 + thickness
            outgoing_cursor[flow["source"]] += thickness

            end_y0 = incoming_cursor[flow["target"]]
            end_y1 = end_y0 + thickness
            incoming_cursor[flow["target"]] += thickness

            x0 = source_layout["x"] + source_layout["width"]
            x1 = target_layout["x"]
            control = max(0.05, (x1 - x0) * 0.45)
            source_color = theme["cycle"][source_layout["level"] % len(theme["cycle"])]
            target_color = theme["cycle"][target_layout["level"] % len(theme["cycle"])]
            flow_color = self._blend_colors(source_color, target_color, 0.5)

            path = MplPath(
                [
                    (x0, start_y0),
                    (x0 + control, start_y0),
                    (x1 - control, end_y0),
                    (x1, end_y0),
                    (x1, end_y1),
                    (x1 - control, end_y1),
                    (x0 + control, start_y1),
                    (x0, start_y1),
                    (x0, start_y0),
                ],
                [
                    MplPath.MOVETO,
                    MplPath.CURVE4,
                    MplPath.CURVE4,
                    MplPath.CURVE4,
                    MplPath.LINETO,
                    MplPath.CURVE4,
                    MplPath.CURVE4,
                    MplPath.CURVE4,
                    MplPath.CLOSEPOLY,
                ],
            )
            ax.add_patch(
                PathPatch(
                    path,
                    facecolor=self._mpl_rgba(flow_color, 0.50),
                    edgecolor=self._mpl_rgba(flow_color, 0.12),
                    linewidth=0.6,
                    zorder=1,
                )
            )

        for node, layout in node_layout.items():
            node_color = theme["cycle"][layout["level"] % len(theme["cycle"])]
            ax.add_patch(
                FancyBboxPatch(
                    (layout["x"], layout["y"]),
                    layout["width"],
                    layout["height"],
                    boxstyle="round,pad=0.003,rounding_size=0.01",
                    facecolor=node_color.name(),
                    edgecolor=self._with_alpha(theme["text"], 70).name(),
                    linewidth=1.0,
                    zorder=3,
                )
            )

            is_last_column = layout["level"] == max_level
            label_x = layout["x"] - 0.012 if is_last_column else layout["x"] + layout["width"] + 0.012
            alignment = "right" if is_last_column else "left"
            ax.text(
                label_x,
                layout["y"] + (layout["height"] / 2),
                self._wrap_label(node, 16, 3),
                ha=alignment,
                va="center",
                color=theme["text"].name(),
                fontsize=8,
                zorder=4,
            )
        return False

    def _render_error_image(self, message):
        palette = get_current_palette()
        theme = self._build_theme(palette)
        self.figure.clear()
        ax = self.figure.add_subplot(111)
        ax.set_facecolor(theme["surface"].name())
        ax.axis("off")
        ax.text(
            0.5,
            0.58,
            "Chart rendering issue",
            ha="center",
            va="center",
            color=theme["text"].name(),
            fontsize=13,
            fontweight="bold",
        )
        ax.text(
            0.5,
            0.42,
            message,
            ha="center",
            va="center",
            color=self._with_alpha(theme["text"], 180).name(),
            fontsize=9,
            wrap=True,
        )
        self.figure.subplots_adjust(left=0.06, right=0.94, top=0.92, bottom=0.10)
        self.chart_image = self._figure_to_image()

    def _figure_to_image(self):
        self.canvas.draw()
        width, height = self.canvas.get_width_height()
        buffer = self.canvas.buffer_rgba()
        return QImage(buffer, width, height, width * 4, QImage.Format.Format_RGBA8888).copy()

    def generate_chart(self):
        """
        Renders the chart using Matplotlib based on the item's data dictionary.
        If generation fails (e.g. malformed data), it displays an error placeholder instead of crashing.
        """
        self.render_timer.stop()
        self.title = self.data.get("title", "Chart")
        self._set_figure_geometry()
        theme = self._build_theme(get_current_palette())

        try:
            self.figure.clear()
            self.figure.patch.set_facecolor(theme["surface"].name())
            ax = self.figure.add_subplot(111)
            chart_data = self._sanitize_chart_data()
            chart_type = chart_data["type"]

            if chart_type == "bar":
                use_tight_layout = self._render_bar_chart(ax, chart_data, theme)
            elif chart_type == "line":
                use_tight_layout = self._render_line_chart(ax, chart_data, theme)
            elif chart_type == "pie":
                use_tight_layout = self._render_pie_chart(ax, chart_data, theme)
            elif chart_type == "histogram":
                use_tight_layout = self._render_histogram(ax, chart_data, theme)
            elif chart_type == "sankey":
                use_tight_layout = self._render_sankey_chart(ax, chart_data, theme)
            else:
                raise ValueError(f"Unsupported chart type: {chart_type}")

            if use_tight_layout:
                self.figure.tight_layout(pad=1.25)

            self.chart_image = self._figure_to_image()
        except Exception as exc:
            self._render_error_image(str(exc))

        self.update()

    def boundingRect(self):
        return QRectF(0, 0, self.width, self.height)

    def paint(self, painter, option, widget=None):
        """Handles the custom painting of the chart item."""
        palette = get_current_palette()
        node_colors = get_graph_node_colors()
        accent = self._header_accent(palette)
        chart_rect = self._chart_rect()

        painter.setRenderHint(QPainter.RenderHint.Antialiasing)
        painter.setRenderHint(QPainter.RenderHint.TextAntialiasing)
        painter.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform)

        shadow_path = QPainterPath()
        shadow_path.addRoundedRect(3, 3, self.width, self.height, 12, 12)
        painter.setPen(Qt.PenStyle.NoPen)
        painter.setBrush(QColor(0, 0, 0, 35))
        painter.drawPath(shadow_path)

        body_path = QPainterPath()
        body_path.addRoundedRect(0, 0, self.width, self.height, 12, 12)
        if self.isSelected():
            outline = node_colors["selected_outline"]
        elif self.hovered:
            outline = node_colors["hover_outline"]
        else:
            outline = node_colors["border"]
        painter.setPen(QPen(outline, 2))
        painter.setBrush(QBrush(node_colors["body_start"]))
        painter.drawPath(body_path)

        header_rect = QRectF(0, 0, self.width, self.HEADER_HEIGHT)
        header_path = QPainterPath()
        header_path.addRoundedRect(header_rect, 12, 12)
        header_gradient = QLinearGradient(header_rect.topLeft(), header_rect.bottomLeft())
        header_gradient.setColorAt(0, accent)
        header_gradient.setColorAt(1, node_colors["header_end"])
        painter.setBrush(QBrush(header_gradient))
        painter.setPen(Qt.PenStyle.NoPen)
        painter.drawPath(header_path)

        painter.setPen(QPen(QColor("#ffffff")))
        painter.setFont(QFont("Segoe UI", 10, QFont.Weight.Bold))
        painter.drawText(header_rect.adjusted(12, 0, -120, 0), Qt.AlignmentFlag.AlignVCenter, self.title)

        badge_rect = QRectF(self.width - 102, 8, 90, 24)
        painter.setPen(QPen(self._with_alpha(QColor("#ffffff"), 65), 1))
        painter.setBrush(QBrush(node_colors["badge_fill"]))
        painter.drawRoundedRect(badge_rect, 12, 12)
        painter.setPen(QPen(QColor("#ffffff")))
        painter.setFont(QFont("Segoe UI", 8, QFont.Weight.DemiBold))
        painter.drawText(badge_rect, Qt.AlignmentFlag.AlignCenter, self._badge_text())

        chart_panel = chart_rect.adjusted(-8, -8, 8, 8)
        painter.setPen(QPen(node_colors["panel_border"], 1))
        painter.setBrush(QBrush(node_colors["panel_fill"]))
        painter.drawRoundedRect(chart_panel, 14, 14)

        if not self.chart_image.isNull():
            painter.drawImage(chart_rect, self.chart_image)

        if self.hovered or self.isSelected():
            handle_size = 10
            handle_rect = QRectF(self.width - handle_size, self.height - handle_size, handle_size, handle_size)
            painter.setPen(QPen(QColor("#ffffff")))
            painter.drawLine(handle_rect.topLeft(), handle_rect.bottomRight())
            painter.drawLine(
                handle_rect.topLeft() + QPointF(0, handle_size / 2),
                handle_rect.topRight() + QPointF(-handle_size / 2, handle_size),
            )

    def hoverEnterEvent(self, event):
        self.hovered = True
        self.update()
        super().hoverEnterEvent(event)

    def hoverLeaveEvent(self, event):
        self.hovered = False
        self.resize_handle_hovered = False
        self.setCursor(Qt.CursorShape.ArrowCursor)
        self.update()
        super().hoverLeaveEvent(event)

    def mousePressEvent(self, event):
        """Starts resizing if the resize handle is clicked."""
        if self._is_resize_handle(event.pos()):
            self.resizing = True
            self.resize_start_pos = event.pos()
            self.resize_start_size = QSizeF(self.width, self.height)
            event.accept()

        if event.button() == Qt.MouseButton.LeftButton and self.scene():
            self.scene().is_dragging_item = True
        super().mousePressEvent(event)

    def mouseReleaseEvent(self, event):
        """Stops resizing."""
        if self.resizing:
            self.resizing = False
            self.generate_chart()
            event.accept()

        if self.scene():
            self.scene().is_dragging_item = False
            self.scene()._clear_smart_guides()
        super().mouseReleaseEvent(event)

    def mouseMoveEvent(self, event):
        """Handles resizing logic during a drag."""
        if self.resizing:
            delta = event.pos() - self.resize_start_pos
            new_width = max(self.MIN_WIDTH, self.resize_start_size.width() + delta.x())
            new_height = max(self.MIN_HEIGHT, self.resize_start_size.height() + delta.y())
            self.prepareGeometryChange()
            self.width = new_width
            self.height = new_height
            self.render_timer.start()
            self.update()
            event.accept()
        else:
            super().mouseMoveEvent(event)

    def _is_resize_handle(self, pos):
        """Checks if a position is within the resize handle's area."""
        return QRectF(self.width - 10, self.height - 10, 10, 10).contains(pos)

    def itemChange(self, change, value):
        """Handles item changes."""
        if change == QGraphicsItem.ItemPositionChange and self.scene() and self.scene().is_dragging_item:
            parent = self.parentItem()
            from .graphite_canvas_container import Container
            if parent and isinstance(parent, Container):
                parent.updateGeometry()
            return self.scene().snap_position(self, value)

        if change == QGraphicsItem.ItemPositionHasChanged and self.scene():
            self.scene().nodeMoved(self)

        return super().itemChange(change, value)
