"""ADR-015 stage 15.7: requirements.txt must always match what pip-compile
would produce from requirements.in right now - catches a requirements.in
edit that was never regenerated into the lock, which is worse than no lock
at all (CI would silently keep installing something requirements.in no
longer actually describes).

Needs pip-tools installed to run for real; skipped (not failed) if it
isn't, since this is opt-in CI/dev tooling - not a hard app dependency -
matching pytest/ruff/mypy's own ad-hoc-install pattern (see pyproject.toml's
[project.optional-dependencies] dev extra and .github/workflows/ci.yml's
own "Install dev tooling" step, which installs pip-tools alongside them
specifically so this test doesn't just skip in CI).
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]


def _lock_body(path: Path) -> list[str]:
    # Skip the autogenerated header's own invocation-echo line - it embeds
    # --output-file=<this file's own name>, which necessarily differs
    # between the committed requirements.txt and a same-content scratch
    # copy regenerated under a different filename, even with zero real
    # drift in the actual dependency content below it.
    return [
        line for line in path.read_text(encoding="utf-8").splitlines(keepends=True)
        if not line.strip().startswith("#    pip-compile")
    ]


def test_requirements_txt_matches_requirements_in(tmp_path):
    if shutil.which("pip-compile") is None:
        pytest.skip("pip-tools not installed - opt-in CI/dev tooling, not a hard dependency")

    scratch = tmp_path / "requirements.check.txt"
    # Seeded from the committed lock so pip-compile's incremental resolver
    # keeps every still-valid existing pin - otherwise a newer transitive
    # release landing on PyPI since the lock was last generated would show
    # up as spurious "drift" unrelated to any real requirements.in change.
    shutil.copy(REPO_ROOT / "requirements.txt", scratch)
    result = subprocess.run(
        ["pip-compile", "--generate-hashes", f"--output-file={scratch}", "requirements.in"],
        cwd=REPO_ROOT, capture_output=True, text=True, timeout=180,
    )
    assert result.returncode == 0, f"pip-compile itself failed:\n{result.stdout}\n{result.stderr}"

    committed = _lock_body(REPO_ROOT / "requirements.txt")
    regenerated = _lock_body(scratch)
    assert committed == regenerated, (
        "requirements.txt is stale relative to requirements.in - run "
        "`pip-compile --generate-hashes --output-file=requirements.txt requirements.in` "
        "(with the same Python version this repo pins, currently 3.12) and commit the result."
    )
