import re
from PySide6.QtCore import QThread, Signal
import graphite_config as config
import api_provider

class ReasoningAgent:
    """
    An agent that uses a multi-step "plan, reason, critique" process to solve
    complex problems that a single LLM call might fail on.
    """
    PLAN_PROMPT = """
You are a methodical planner. Your task is to break down a complex user query into a series of simple, actionable steps. Each step should represent a single thought process or question that builds towards the final answer.

RULES:
- Output this plan as a numbered list (e.g., "1. First step...").
- Do NOT attempt to answer the query yet.
- Each step should be a clear, self-contained instruction or question.
- The plan should logically flow from one step to the next.
- The final step should always be to synthesize the previous steps into a final answer.
"""

    REASON_PROMPT = """
You are a reasoning engine executing one step of a larger plan.
You will be given the branch context, the original query, the full plan, the history of previous thoughts, and the current step to execute.

RULES:
- Your task is to focus EXCLUSIVELY on the CURRENT step.
- Use the 'Branch Context', 'Original Query', and 'Thought History' for context.
- Provide a detailed, self-contained answer for the current step.
- Do NOT solve the entire problem. Only address the single step you are given.
- Think through your response clearly and logically.
"""

    CRITIQUE_PROMPT = """
You are a critical analyst. Your task is to review a 'thought' generated by another AI to find flaws.

RULES:
1.  **Review the Thought:** Read the thought in the context of the branch context and the original query.
2.  **Identify Weaknesses:** Check for logical fallacies, missing information, incorrect assumptions, or alternative perspectives. Ask critical questions like:
    - Is this assumption valid?
    - What is the counter-argument?
    - Is there a simpler explanation?
    - What evidence is missing?
3.  **Provide a Refined Thought:** Based on your critique, provide a new, improved version of the thought. It should be more robust, logical, and complete.
4.  **Format:** Your output MUST be in this format:
    **Critique:** [Your brief, bulleted critique of the original thought.]
    **Refined Thought:** [Your new, improved version of the thought.]
"""

    SYNTHESIZE_PROMPT = """
You are a synthesis expert. You have been provided with branch context, a user's original query, and a series of vetted, refined 'thoughts' that break down the problem.

RULES:
- Your task is to weave these thoughts together into a single, comprehensive, and well-structured final answer.
- Do not just list the thoughts; synthesize them into a coherent narrative that directly addresses the user's original query.
- Use clear markdown formatting (headings, lists, bold text) for readability.
- The final answer should be self-contained and understandable without needing to read the intermediate thoughts.
"""

    def run_step(self, system_prompt: str, user_prompt: str) -> str:
        """
        Executes a single LLM call for one step of the reasoning process.

        Args:
            system_prompt (str): The system prompt defining the agent's role for this step.
            user_prompt (str): The user prompt containing the context and current task.

        Returns:
            str: The AI's response for this step.
        """
        try:
            response = api_provider.chat(
                task=config.TASK_CHAT,
                messages=[
                    {'role': 'system', 'content': system_prompt},
                    {'role': 'user', 'content': user_prompt}
                ]
            )
            return response['message']['content']
        except Exception as e:
            raise RuntimeError(f"API call failed during reasoning step: {e}")


class ReasoningWorkerThread(QThread):
    """Orchestrates the ReasoningAgent's workflow in a background thread."""
    step_finished = Signal(str, str) # title, text
    finished = Signal(str) # final_answer
    error = Signal(str)

    def __init__(self, agent: ReasoningAgent, original_prompt: str, budget: int, branch_context: str = ""):
        super().__init__()
        self.agent = agent
        self.original_prompt = original_prompt
        self.budget = budget # The number of "reason -> critique" cycles.
        self.branch_context = branch_context or "No prior branch context."
        self._is_running = True

    def run(self):
        """Executes the full multi-step reasoning workflow."""
        try:
            if not self._is_running: return

            # 1. Create a plan based on the original prompt.
            plan_user_prompt = (
                f"Branch Context:\n{self.branch_context}\n\n"
                f"Original Query: \"{self.original_prompt}\"\n\n"
                "Create a step-by-step plan to answer this query."
            )
            plan_str = self.agent.run_step(self.agent.PLAN_PROMPT, plan_user_prompt)
            # Parse the numbered list from the plan string.
            plan_steps = [f"{i}. {step.strip()}" for i, step in enumerate(re.split(r'\d+\.\s*', plan_str)) if step.strip()]
            self.step_finished.emit("Step 1: The Plan", "\n".join(plan_steps))
            
            thought_history = []
            
            # 2. Iterate through the plan for the number of steps defined by the "thinking budget".
            for i in range(self.budget):
                if not self._is_running: return
                
                # Use modulo to loop through plan steps if the budget is larger than the plan.
                step_index = i % len(plan_steps)
                current_step = plan_steps[step_index]

                # 2a. Execute the "Reason" step.
                reason_user_prompt = (
                    f"Branch Context:\n{self.branch_context}\n\n"
                    f"Original Query: \"{self.original_prompt}\"\n\n"
                    f"Full Plan:\n{plan_str}\n\n"
                    f"Thought History:\n{''.join(thought_history) or 'No thoughts yet.'}\n\n"
                    f"CURRENT STEP TO EXECUTE: {current_step}"
                )
                initial_thought = self.agent.run_step(self.agent.REASON_PROMPT, reason_user_prompt)

                if not self._is_running: return

                # 2b. Execute the "Critique" step on the previous thought.
                critique_user_prompt = (
                    f"Branch Context:\n{self.branch_context}\n\n"
                    f"Original Query: \"{self.original_prompt}\"\n\n"
                    f"Thought to Critique:\n{initial_thought}"
                )
                critique_response = self.agent.run_step(self.agent.CRITIQUE_PROMPT, critique_user_prompt)
                
                # Parse the refined thought from the critique response.
                refined_thought = critique_response
                if "Refined Thought:" in critique_response:
                    parts = critique_response.split("Refined Thought:", 1)
                    if len(parts) > 1:
                        refined_thought = parts[1].strip()

                # Add the refined thought to the history for the next step.
                thought_history.append(f"Thought on '{current_step}':\n{refined_thought}\n\n")
                self.step_finished.emit(f"Step {i+2}: {current_step}", critique_response)

            if not self._is_running: return

            # 3. Synthesize the final answer from the history of refined thoughts.
            synthesis_user_prompt = (
                f"Branch Context:\n{self.branch_context}\n\n"
                f"Original Query: \"{self.original_prompt}\"\n\n"
                f"Full History of Refined Thoughts:\n{''.join(thought_history)}"
            )
            final_answer = self.agent.run_step(self.agent.SYNTHESIZE_PROMPT, synthesis_user_prompt)
            
            if self._is_running:
                self.finished.emit(final_answer)

        except Exception as e:
            if self._is_running:
                self.error.emit(str(e))
        finally:
            self._is_running = False

    def stop(self):
        """Stops the thread safely."""
        self._is_running = False
