import { useEffect, useState } from "react";
import type { WsTransport } from "../../lib/ws/transport";
import { TOPIC_VALIDATORS } from "../../lib/api-contract/topics";
import type { AppPluginGrant, AppPluginsState } from "../../lib/bridge-core/generated/app-plugins-state";
import type { AppSettingsState, McpServerConfig } from "../../lib/bridge-core/generated/app-settings-state";
import { useExecutionLimits } from "../canvas/ExecutionLimitsContext";
import { Dialog, useOverlays } from "../overlays/overlays";
import { CustomSelect } from "./CustomSelect";

/**
 * The settings dialog (Qt-removal plan R2.5d, extended R7.4a-c) - settings
 * island's SPA successor. Every page R2.5d originally deferred is real now:
 * General, Integrations, API-provider, Ollama, and (R7.4c) Llama.cpp. The
 * Ollama page's own "Scan Folder..." button, deferred alongside Llama.cpp
 * pending a native folder-picker capability, is real too - see
 * backend/native_dialogs.py's docstring for the mechanism.
 */

const SECTIONS = [
  "General",
  "Ollama (Local)",
  "Llama.cpp (Local)",
  "API Endpoint",
  "Integrations",
  "MCP Servers",
  "Plugins",
  "Resource Limits",
] as const;
type Section = (typeof SECTIONS)[number];

// Mirrors graphlink_task_config.py's TASK_* constants - the same 5-slot set
// backend/settings.py's _OLLAMA_TASK_KEYS uses (task_image_gen is absent:
// Ollama has no image-generation path).
const OLLAMA_TASKS = ["task_chat", "task_title", "task_chart", "task_web_validate", "task_web_summarize"] as const;
const OLLAMA_TASK_LABELS: Record<(typeof OLLAMA_TASKS)[number], string> = {
  task_chat: "Chat Model",
  task_title: "Chat Naming Model",
  task_chart: "Chart Generation Model",
  task_web_validate: "Web Content Validation Model",
  task_web_summarize: "Web Content Summarization Model",
};
const OLLAMA_MODELS_DATALIST_ID = "settings-ollama-scanned-models";
const LLAMA_CPP_MODELS_DATALIST_ID = "settings-llama-cpp-scanned-models";

// R8a: reasoning went from a 2-value Mode (Thinking/Quick) to a graded
// 4-value Level shared by both local providers here and the composer's own
// Reasoning popover (backend/composer.py's REASONING_OPTIONS) - same ids,
// same labels, so a user never has to learn two different vocabularies.
const REASONING_LEVEL_OPTIONS = [
  { id: "off", label: "Off" },
  { id: "low", label: "Low" },
  { id: "medium", label: "Medium" },
  { id: "high", label: "High" },
] as const;

// ADR-018 stage 18.4: mirrors graphlink_model_catalog.AUTO_POLICIES - the
// policy the auto rung of the resolution chain applies when neither an
// explicit task assignment nor a node/branch pin resolves a model.
const AUTO_MODEL_POLICY_OPTIONS = [
  { id: "cheapest-capable", label: "Cheapest Capable" },
  { id: "fastest", label: "Fastest" },
  { id: "best-quality", label: "Best Quality" },
] as const;

// ADR-012 stage 12.2: mirrors SettingsManager.THEMES (graphlink_settings_store.py).
const THEME_OPTIONS = [
  { id: "system", label: "Match System" },
  { id: "light", label: "Light" },
  { id: "dark", label: "Dark" },
] as const;

// Llama.cpp has no per-task assignment concept like Ollama's OLLAMA_TASKS -
// just one global chat model path plus an optional title/naming override
// (api_provider.py's _get_llama_cpp_model_path: chart/web-validate/web-
// summarize all silently fall back to the chat model path).
function basename(path: string): string {
  return path.split(/[\\/]/).pop() || path;
}

const NOTIFICATION_TYPE_LABELS: Record<string, string> = {
  info: "Info",
  success: "Success",
  warning: "Warning",
  error: "Error",
};

// Mirrors graphlink_task_config.py's MODE_OLLAMA_LOCAL / MODE_LLAMACPP_LOCAL
// / MODE_API_ENDPOINT constants exactly - the wire values state.providerMode
// carries and setProviderMode validates against (backend/api/
// intents_settings_general.py's _KNOWN_PROVIDER_MODES). Same hand-
// maintained-constant convention as API_PROVIDER_* below. Deliberately NOT
// read off of SECTIONS above even though the 3 labels happen to coincide -
// SECTIONS is UI navigation (it also has "General"/"Integrations", which
// are not provider modes at all), this is the closed provider-mode
// vocabulary; keeping them separate means a future SECTIONS edit can't
// silently change what a mode comparison means.
const MODE_OLLAMA_LOCAL = "Ollama (Local)";
const MODE_LLAMACPP_LOCAL = "Llama.cpp (Local)";
const MODE_API_ENDPOINT = "API Endpoint";

// Mirrors graphlink_task_config.py's API_PROVIDER_* constants exactly (the
// wire values backend/settings.py's SettingsManager persists) - not an enum
// generated by codegen since these 3 strings are the whole of a small,
// stable, hand-maintained set, the same convention SECTIONS above follows.
const API_PROVIDER_OPENAI = "OpenAI-Compatible";
const API_PROVIDER_ANTHROPIC = "Anthropic Claude";
const API_PROVIDER_GEMINI = "Google Gemini";
const API_PROVIDERS = [API_PROVIDER_OPENAI, API_PROVIDER_ANTHROPIC, API_PROVIDER_GEMINI] as const;
// Mirrors SettingsManager.get_api_base_url()'s own default (graphlink_settings_store.py).
const DEFAULT_OPENAI_BASE_URL = "https://api.openai.com/v1";

// Mirrors graphlink_task_config.py's TASK_* constants exactly.
const TASK_TITLE = "task_title";
const TASK_CHAT = "task_chat";
const TASK_CHART = "task_chart";
const TASK_IMAGE_GEN = "task_image_gen";
const TASK_WEB_VALIDATE = "task_web_validate";
const TASK_WEB_SUMMARIZE = "task_web_summarize";

const API_TASK_FIELDS: { task: string; label: string }[] = [
  { task: TASK_TITLE, label: "Chat Naming / Session Title" },
  { task: TASK_CHAT, label: "Chat, Explain, Takeaways (main model)" },
  { task: TASK_CHART, label: "Chart Generation (code-capable model)" },
  { task: TASK_IMAGE_GEN, label: "Image Generation" },
  { task: TASK_WEB_VALIDATE, label: "Web Content Validation" },
  { task: TASK_WEB_SUMMARIZE, label: "Web Content Summarization" },
];

const initialState: AppSettingsState = {
  schemaVersion: 1,
  minCompatibleSchemaVersion: 1,
  revision: 0,
  activeSection: "General",
  showTokenCounter: true,
  enableSystemPrompt: true,
  notificationPreferences: {},
  githubTokenConfigured: false,
  // ADR-004 stage 4.4: optimistic default (true = encrypted) so the
  // persistent badge below never flashes a false warning before the
  // first real snapshot arrives - the real backend value replaces this
  // on the very first "app-settings" publish, same as every other field
  // here.
  secretsEncryptedAtRest: true,
  // ADR-016 stage 16.1: mirrors SettingsManager.get_log_level()'s own default.
  logLevel: "INFO",
  // ADR-018 stage 18.4: mirrors SettingsManager.get_auto_model_policy()'s
  // own default.
  autoModelPolicy: "cheapest-capable",
  // ADR-012 stage 12.2: mirrors SettingsManager.get_theme()'s own default.
  theme: "system",
  // ADR-012 stage 12.6: mirrors SettingsManager.get_has_completed_onboarding()'s
  // own default - OnboardingDialog.tsx is the surface that actually acts on
  // this; SettingsDialog only needs it to satisfy the shared contract.
  hasCompletedOnboarding: false,
  // ADR-012 stage 12.6: mirrors SettingsManager.get_current_mode()'s own default.
  providerMode: MODE_OLLAMA_LOCAL,
  activeApiProvider: API_PROVIDER_OPENAI,
  viewingApiProvider: API_PROVIDER_OPENAI,
  apiBaseUrl: DEFAULT_OPENAI_BASE_URL,
  apiKeyConfigured: { openai: false, anthropic: false, gemini: false },
  apiKeySource: { openai: "none", anthropic: "none", gemini: "none" },
  apiModels: {},
  apiModelCatalog: [],
  apiCatalogStatus: "idle",
  apiCatalogMessage: "Model catalog has not been refreshed yet.",
  geminiStaticModels: [],
  geminiStaticImageModels: [],
  ollamaReasoningLevel: "high",
  ollamaCurrentModel: "",
  ollamaModelAssignments: {},
  ollamaScannedModels: [],
  ollamaScanSummary: "",
  ollamaScanStatus: "idle",
  ollamaPullStatus: "idle",
  ollamaNotice: "",
  llamaCppReasoningLevel: "high",
  llamaCppChatModelPath: "",
  llamaCppTitleModelPath: "",
  llamaCppChatFormat: "",
  llamaCppNCtx: 4096,
  llamaCppNGpuLayers: 0,
  llamaCppNThreads: 0,
  llamaCppScannedModels: [],
  llamaCppScanSummary: "",
  llamaCppScanStatus: "idle",
  llamaCppNotice: "",
  // ADR-012 stage 12.6: mirrors SettingsManager.get_mcp_servers()'s own default.
  mcpServers: [],
};

const initialPluginsState: AppPluginsState = {
  schemaVersion: 1,
  minCompatibleSchemaVersion: 1,
  revision: 0,
  categories: [],
  // ADR-014 stage 14.4: one entry per discovered NON-built-in plugin (see
  // backend/plugins.py's plugin_registry.picker_entries/node_kinds split vs.
  // builtin_actions, and AppPluginGrantPayload's own docstring in
  // contracts/graphlink_app_plugins_payload.py for the "one row per
  // distinct plugin_id" construction rule) - built-ins never appear here.
  grants: [],
};

function sectionKey(section: Section): string {
  // Backend storage is UI-navigation-only for this field (mirrors the
  // legacy bridge - see backend/settings.py's active_section cell), so any
  // stable string works; reusing the display name keeps the wire traffic
  // human-readable in the WS inspector.
  return section === "General" ? "general" : section === "Integrations" ? "integrations" : section.toLowerCase();
}

function GeneralPage({
  state,
  transport,
}: {
  state: AppSettingsState;
  transport: WsTransport;
}) {
  // R8a (UI/UX issue list finding #9) removed the prior Theme select
  // (Dark/Muted/Monochromatic): it persisted a real setTheme intent, but
  // nothing in the SPA ever applied the value - no data-theme attribute, no
  // alternate token set, the app rendered identically no matter what was
  // selected. A persisted preference that provably does nothing is worse
  // than no preference at all, so it was cut rather than left inert.
  // ADR-012 stages 12.1 (a real light+dark token palette) and 12.2 (this
  // control, plus App.tsx's own applyTheme effect) resolve exactly that gap
  // - system/light/dark all genuinely repaint the app now.
  const overlays = useOverlays();
  return (
    <div className="settings-general-page">
      <div className="settings-field">
        <span className="settings-field-label">Theme</span>
        <CustomSelect
          ariaLabel="Theme"
          value={state.theme}
          options={THEME_OPTIONS.map((option) => ({ id: option.id, label: option.label }))}
          onChange={(id) => transport.fireIntent("app-settings", "setTheme", [id], undefined, true)}
        />
      </div>

      <label className="settings-checkbox-row">
        <input
          type="checkbox"
          checked={state.showTokenCounter}
          onChange={(event) => transport.fireIntent("app-settings", "setShowTokenCounter", [event.target.checked], undefined, true)}
        />
        Show Token Counter Overlay
      </label>

      <label className="settings-checkbox-row">
        <input
          type="checkbox"
          checked={state.enableSystemPrompt}
          onChange={(event) => transport.fireIntent("app-settings", "setEnableSystemPrompt", [event.target.checked], undefined, true)}
        />
        Enable Assistant System Prompt
      </label>

      <div className="settings-field">
        <span className="settings-field-label">Automatic Model Selection Policy</span>
        <CustomSelect
          ariaLabel="Automatic Model Selection Policy"
          value={state.autoModelPolicy}
          options={AUTO_MODEL_POLICY_OPTIONS.map((option) => ({ id: option.id, label: option.label }))}
          onChange={(id) => transport.fireIntent("app-settings", "setAutoModelPolicy", [id], undefined, true)}
        />
        <p className="settings-field-hint">
          Used when a task has no explicitly assigned model and no node/branch pin - picks the cheapest, fastest,
          or highest-quality capable model from your configured providers.
        </p>
      </div>

      <fieldset className="settings-fieldset">
        <legend>Notification types</legend>
        {Object.keys(NOTIFICATION_TYPE_LABELS).map((type) => (
          <label className="settings-checkbox-row" key={type}>
            <input
              type="checkbox"
              checked={state.notificationPreferences[type] ?? true}
              onChange={(event) =>
                transport.fireIntent("app-settings", "setNotificationPreference", [type, event.target.checked], undefined, true)
              }
            />
            {NOTIFICATION_TYPE_LABELS[type]}
          </label>
        ))}
      </fieldset>

      {/* ADR-012 stage 12.6: manual re-entry to the first-run onboarding
          wizard (OnboardingDialog.tsx) - it auto-opens exactly once (a
          fresh machine's hasCompletedOnboarding defaults false) and never
          shows itself again on its own, so this button is the only way
          back to it afterward - the "still reachable manually" entry point,
          matching how Help's own AppBar chip is a standing way back into
          that dialog. */}
      <div className="settings-field">
        <span className="settings-field-label">Onboarding</span>
        <div className="settings-button-row">
          <button type="button" className="settings-button" onClick={() => overlays.open("onboarding", "dialog")}>
            Show Onboarding
          </button>
        </div>
      </div>
    </div>
  );
}

function IntegrationsPage({
  state,
  transport,
}: {
  state: AppSettingsState;
  transport: WsTransport;
}) {
  const [draftToken, setDraftToken] = useState("");

  return (
    <div className="settings-general-page">
      <p className="settings-integrations-intro">
        Store optional external-service tokens used by specialized plugins. The Gitlink plugin uses a GitHub
        personal access token to load your private repositories - if you leave this empty, it still works with
        public repositories.
      </p>

      <label className="settings-field">
        <span className="settings-field-label">GitHub Personal Access Token</span>
        <input
          type="password"
          className="settings-select"
          placeholder="ghp_... or fine-grained token"
          value={draftToken}
          onChange={(event) => setDraftToken(event.target.value)}
        />
      </label>

      <p className="settings-update-status">
        {state.githubTokenConfigured ? "A GitHub token is currently configured." : "No GitHub token configured."}
      </p>

      <div className="settings-button-row">
        <button
          type="button"
          className="settings-button"
          onClick={() => {
            transport.fireIntent("app-settings", "clearGithubToken", []);
            setDraftToken("");
          }}
        >
          Clear Token
        </button>
        <button
          type="button"
          className="settings-button settings-button-primary"
          disabled={draftToken.trim().length === 0}
          onClick={() => {
            transport.fireIntent("app-settings", "setGithubToken", [draftToken]);
            setDraftToken("");
          }}
        >
          Save Integrations
        </button>
      </div>
    </div>
  );
}

// ADR-012 stage 12.6: the provider-mode switcher itself. Lives on each of
// the 3 mode pages (below) rather than as a standalone control elsewhere -
// see this file's module docstring for the reasoning. One shared component
// so the copy/behavior can't drift between the 3 call sites; only the mode
// string and the page it's embedded in differ.
//
// Fires setProviderMode WITHOUT the queueable flag most of this dialog's
// other controls pass (contrast GeneralPage's setTheme, etc.) - unlike a
// plain settings value, a mode switch has a real live side effect
// (apply_provider_mode constructs/verifies a provider client, possibly
// against an unreachable local daemon) and can genuinely fail, matching
// the non-queueable convention this file already uses for Save
// Configuration/System Scan/Validate and Pull Model rather than the
// idempotent-setting one.
function ProviderModeSwitch({ mode, state, transport }: { mode: string; state: AppSettingsState; transport: WsTransport }) {
  const isActive = state.providerMode === mode;
  return (
    <div className="settings-field">
      <p className="settings-update-status" data-level={isActive ? undefined : "warning"}>
        {isActive
          ? `${mode} is the active provider mode.`
          : `${mode} is configured here, but ${state.providerMode} is the active provider mode.`}
      </p>
      {!isActive && (
        <div className="settings-button-row">
          <button
            type="button"
            className="settings-button settings-button-primary"
            onClick={() => transport.fireIntent("app-settings", "setProviderMode", [mode])}
          >
            Use This Provider
          </button>
        </div>
      )}
    </div>
  );
}

function ApiProviderPage({
  state,
  transport,
}: {
  state: AppSettingsState;
  transport: WsTransport;
}) {
  const viewingProvider = state.viewingApiProvider;
  const isOpenAi = viewingProvider === API_PROVIDER_OPENAI;
  const isAnthropic = viewingProvider === API_PROVIDER_ANTHROPIC;

  // Draft fields, not server state - mirrors IntegrationsPage's draftToken:
  // the key is write-only (never pre-filled from state, unlike the legacy
  // QWidget - see this file's module docstring for why), and base
  // URL/per-task models are a local edit buffer until Save commits them.
  // Re-synced from the server snapshot whenever the VIEWED provider changes,
  // matching the legacy dialog's own per-provider field reset. Uses React's
  // "adjusting state when a prop changes" pattern (comparing against a
  // tracked previous value INSIDE render, not a useEffect) so a genuine
  // provider switch resets the drafts in the same render/commit rather than
  // flashing the old provider's stale draft for one extra frame first.
  const [draftApiKey, setDraftApiKey] = useState("");
  const [draftBaseUrl, setDraftBaseUrl] = useState(state.apiBaseUrl);
  const [draftModels, setDraftModels] = useState<Record<string, string>>(state.apiModels);
  const [confirmingReset, setConfirmingReset] = useState(false);
  const [lastViewingProvider, setLastViewingProvider] = useState(viewingProvider);

  if (viewingProvider !== lastViewingProvider) {
    setLastViewingProvider(viewingProvider);
    setDraftApiKey("");
    setDraftBaseUrl(state.apiBaseUrl);
    setDraftModels(state.apiModels);
    // Don't leave a Reset armed across a provider switch.
    setConfirmingReset(false);
  }

  const catalogModelIds = state.apiModelCatalog.map((entry) => entry.modelId);
  const modelOptionsFor = (task: string): string[] => {
    if (isOpenAi || isAnthropic) return catalogModelIds;
    return task === TASK_IMAGE_GEN ? state.geminiStaticImageModels : state.geminiStaticModels;
  };

  // ADR-006 stage 6.5: Image Generation is optional for EVERY provider, not
  // just Anthropic - image generation is capability-gated at call time on the
  // backend, so a text-only OpenAI-compatible endpoint saves cleanly. The
  // field itself stays visible (and labeled optional) for non-Anthropic
  // providers below; Anthropic keeps hiding it entirely (no image path at all).
  const requiredTasks = API_TASK_FIELDS.filter(({ task }) => task !== TASK_IMAGE_GEN);
  // ADR-004 stage 4.4: the same provider-key derivation apiKeyConfigured's
  // placeholder below already needed, factored out so apiKeySource's new
  // "provided by environment" hint reads the identical key - one place
  // deciding "which of the 3 wire dicts' entries describes the viewed
  // provider", not two that could silently diverge.
  const viewingProviderKey = isOpenAi ? "openai" : isAnthropic ? "anthropic" : "gemini";

  return (
    <div className="settings-general-page">
      {/* ADR-012 stage 12.6: whether "API Endpoint" itself (as opposed to
          Ollama/Llama.cpp) is the active provider MODE - distinct from, and
          rendered above, the activeApiProvider status paragraph just below
          it, which compares which of the 3 CLOUD providers (OpenAI/
          Anthropic/Gemini) is active and only means anything once this
          mode already is. */}
      <ProviderModeSwitch mode={MODE_API_ENDPOINT} state={state} transport={transport} />

      <div className="settings-field">
        <span className="settings-field-label">API Provider</span>
        <CustomSelect
          ariaLabel="API Provider"
          value={viewingProvider}
          options={API_PROVIDERS.map((provider) => ({ id: provider, label: provider }))}
          onChange={(id) => transport.fireIntent("app-settings", "setViewingApiProvider", [id], undefined, true)}
        />
      </div>

      <p className="settings-update-status">
        {viewingProvider === state.activeApiProvider
          ? `${state.activeApiProvider} is the currently active provider.`
          : `Currently active: ${state.activeApiProvider}. Save to switch to ${viewingProvider}.`}
      </p>

      {isOpenAi && (
        <label className="settings-field">
          <span className="settings-field-label">Base URL</span>
          <input
            type="text"
            className="settings-select"
            placeholder="https://api.openai.com/v1"
            value={draftBaseUrl}
            onChange={(event) => setDraftBaseUrl(event.target.value)}
          />
        </label>
      )}

      <label className="settings-field">
        <span className="settings-field-label">API Key</span>
        <input
          type="password"
          className="settings-select"
          placeholder={
            (state.apiKeyConfigured as Record<string, boolean>)[viewingProviderKey]
              ? "A key is configured - enter a new one to replace it"
              : "Enter your API key..."
          }
          value={draftApiKey}
          onChange={(event) => setDraftApiKey(event.target.value)}
        />
        {/* ADR-004 stage 4.4: surfaces api_provider.py's own env-var key
            fallback, previously invisible. apiKeySource[viewingProviderKey]
            reflects the VIEWED provider (per its own dropdown), which may
            not be the ACTIVE one - so this is a prediction ("if you saved/
            activated this provider, its key would come from the
            environment"), not a claim that the environment is supplying a
            key to a live request right now. "stored" whenever a saved key
            already exists (a stored key always wins over the environment -
            see backend/settings.py's own _api_key_source). Saving a key
            here will switch this to "stored" on the next snapshot, same as
            apiKeyConfigured already does. */}
        {(state.apiKeySource as Record<string, string>)[viewingProviderKey] === "environment" && (
          <span className="settings-field-hint">
            Key provided by an environment variable, not Settings.
          </span>
        )}
      </label>

      {(isOpenAi || isAnthropic) && (
        <>
          <div className="settings-button-row">
            <button
              type="button"
              className="settings-button"
              disabled={state.apiCatalogStatus === "loading"}
              onClick={() =>
                transport.fireIntent("app-settings", "loadApiModels", [viewingProvider, draftApiKey, draftBaseUrl])
              }
            >
              {state.apiCatalogStatus === "loading" ? "Loading catalog…" : "Load Available Models"}
            </button>
          </div>
          <p
            className="settings-update-status"
            data-level={state.apiCatalogStatus === "error" ? "warning" : undefined}
          >
            {state.apiCatalogMessage}
          </p>
        </>
      )}

      <fieldset className="settings-fieldset">
        <legend>Model Selection (per task)</legend>
        {API_TASK_FIELDS.filter(({ task }) => !(isAnthropic && task === TASK_IMAGE_GEN)).map(({ task, label }) => (
          <label className="settings-field" key={task}>
            {/* Same "(optional)" suffix convention as the Llama.cpp page's
                Chat Naming File field. */}
            <span className="settings-field-label">{task === TASK_IMAGE_GEN ? `${label} (optional)` : label}</span>
            <input
              type="text"
              className="settings-select"
              list={`api-model-options-${task}`}
              placeholder="Select or type a model..."
              value={draftModels[task] ?? ""}
              onChange={(event) => setDraftModels((prev) => ({ ...prev, [task]: event.target.value }))}
            />
            <datalist id={`api-model-options-${task}`}>
              {modelOptionsFor(task).map((modelId) => (
                <option key={modelId} value={modelId} />
              ))}
            </datalist>
          </label>
        ))}
      </fieldset>

      {confirmingReset && (
        <p className="settings-update-status" data-level="error">
          This clears all saved API keys and model configurations and cannot be undone.
        </p>
      )}

      <div className="settings-button-row">
        {/* Reset wipes every provider's key irreversibly. Legacy gated it
            behind a "This cannot be undone" Yes/No prompt; this is the same
            two-step confirm the legacy settings island and ChatLibraryDialog
            already use, rather than a one-click destructive button. */}
        {confirmingReset ? (
          <>
            <button type="button" className="settings-button" onClick={() => setConfirmingReset(false)}>
              Cancel
            </button>
            <button
              type="button"
              className="settings-button settings-button-primary"
              onClick={() => {
                transport.fireIntent("app-settings", "resetApiSettings", []);
                // Reset must clear the local drafts too, not just the key:
                // the resync block only fires on a viewingProvider change,
                // which Reset doesn't cause, so stale draftBaseUrl/
                // draftModels would otherwise survive and a later Save
                // would re-persist exactly what Reset just cleared.
                setDraftApiKey("");
                setDraftBaseUrl(DEFAULT_OPENAI_BASE_URL);
                setDraftModels({});
                setConfirmingReset(false);
              }}
            >
              Confirm Reset
            </button>
          </>
        ) : (
          <button type="button" className="settings-button" onClick={() => setConfirmingReset(true)}>
            Reset API Settings
          </button>
        )}
        <button
          type="button"
          className="settings-button settings-button-primary"
          disabled={
            draftApiKey.trim().length === 0 ||
            requiredTasks.some(({ task }) => !(draftModels[task] ?? "").trim())
          }
          onClick={() => {
            transport.fireIntent("app-settings", "saveApiConfiguration", [
              viewingProvider,
              draftBaseUrl,
              draftApiKey,
              draftModels,
            ]);
            setDraftApiKey("");
          }}
        >
          Save Configuration
        </button>
      </div>
    </div>
  );
}

// The flat wire value ("inherit"|"auto"|"<explicit model id>") maps onto two
// UI controls: a mode select (mirrors the legacy island's 3 special combo
// entries) and a conditionally-shown text input for the explicit case. This
// is a deliberate 2-control simplification of the legacy single editable
// combo, ported verbatim from web_ui/src/islands/settings/App.tsx's own
// OllamaTaskField.
function OllamaTaskField({
  task,
  value,
  transport,
}: {
  task: (typeof OLLAMA_TASKS)[number];
  value: string;
  transport: WsTransport;
}) {
  const isSpecial = value === "inherit" || value === "auto";
  const [uiMode, setUiMode] = useState(isSpecial ? value : "explicit");
  const [prevValue, setPrevValue] = useState(value);

  if (value !== prevValue) {
    setPrevValue(value);
    setUiMode(isSpecial ? value : "explicit");
  }

  const modeOptions = [
    ...(task !== "task_chat" ? [{ id: "inherit", label: "Use chat model" }] : []),
    { id: "auto", label: "Auto - choose a compatible installed model" },
    { id: "explicit", label: "Custom model ID..." },
  ];

  return (
    <>
      <div className="settings-field">
        <span className="settings-field-label">{OLLAMA_TASK_LABELS[task]}</span>
        <CustomSelect
          ariaLabel={OLLAMA_TASK_LABELS[task]}
          value={uiMode}
          options={modeOptions}
          onChange={(nextMode) => {
            setUiMode(nextMode);
            if (nextMode !== "explicit") {
              transport.fireIntent("app-settings", "setOllamaModelAssignment", [task, nextMode], undefined, true);
            }
          }}
        />
      </div>
      {uiMode === "explicit" && (
        <label className="settings-field">
          <span className="settings-field-label">{OLLAMA_TASK_LABELS[task]} (custom model ID)</span>
          <input
            type="text"
            className="settings-select"
            list={OLLAMA_MODELS_DATALIST_ID}
            value={isSpecial ? "" : value}
            onChange={(event) => transport.fireIntent("app-settings", "setOllamaModelAssignment", [task, event.target.value], undefined, true)}
          />
        </label>
      )}
    </>
  );
}

function OllamaPage({ state, transport }: { state: AppSettingsState; transport: WsTransport }) {
  const [draftPullModel, setDraftPullModel] = useState("");

  return (
    <div className="settings-general-page">
      <ProviderModeSwitch mode={MODE_OLLAMA_LOCAL} state={state} transport={transport} />

      <fieldset className="settings-fieldset">
        <legend>Reasoning Level</legend>
        {REASONING_LEVEL_OPTIONS.map((option) => (
          <label className="settings-checkbox-row" key={option.id}>
            <input
              type="radio"
              name="ollama-reasoning-level"
              checked={state.ollamaReasoningLevel === option.id}
              onChange={() => transport.fireIntent("app-settings", "setOllamaReasoningLevel", [option.id], undefined, true)}
            />
            {option.label}
          </label>
        ))}
      </fieldset>

      <p className="settings-update-status">
        Current Active Model: <strong>{state.ollamaCurrentModel || "Auto - no compatible installed model found"}</strong>
      </p>

      <div className="settings-button-row">
        <button
          type="button"
          className="settings-button"
          disabled={state.ollamaScanStatus === "running"}
          onClick={() => transport.fireIntent("app-settings", "scanOllamaSystem", [])}
        >
          {state.ollamaScanStatus === "running" ? "Scanning..." : "System Scan"}
        </button>
        <button
          type="button"
          className="settings-button"
          disabled={state.ollamaScanStatus === "running"}
          onClick={() => transport.fireIntent("app-settings", "pickOllamaScanFolder", [])}
        >
          Scan Folder...
        </button>
      </div>
      <p className="settings-update-status">{state.ollamaScanSummary}</p>

      <datalist id={OLLAMA_MODELS_DATALIST_ID}>
        {state.ollamaScannedModels.map((model) => (
          <option key={model} value={model} />
        ))}
      </datalist>

      <fieldset className="settings-fieldset">
        <legend>Model Selection (per task)</legend>
        {OLLAMA_TASKS.map((task) => (
          <OllamaTaskField
            key={task}
            task={task}
            value={state.ollamaModelAssignments[task] ?? "auto"}
            transport={transport}
          />
        ))}
      </fieldset>

      <label className="settings-field">
        <span className="settings-field-label">Validate and Pull Model</span>
        <input
          type="text"
          className="settings-select"
          list={OLLAMA_MODELS_DATALIST_ID}
          placeholder="Advanced model ID entry"
          value={draftPullModel}
          onChange={(event) => setDraftPullModel(event.target.value)}
        />
      </label>
      <div className="settings-button-row">
        <button
          type="button"
          className="settings-button settings-button-primary"
          disabled={draftPullModel.trim().length === 0 || state.ollamaPullStatus === "running"}
          onClick={() => transport.fireIntent("app-settings", "pullOllamaModel", [draftPullModel])}
        >
          {state.ollamaPullStatus === "running" ? "Validating..." : "Validate and Pull Model"}
        </button>
      </div>

      {state.ollamaNotice && (
        <p className="settings-update-status" data-level="error">
          {state.ollamaNotice}
        </p>
      )}
    </div>
  );
}

// Llama.cpp's runtime tunables (chat format, n_ctx, n_gpu_layers, n_threads)
// persist on every change - no separate Save step, unlike the model-path
// fields below. A plain value={state.llamaCpp*} binding (no local buffer)
// breaks multi-character typing: the fake test transport (and, over a real
// WS round trip, ordinary network latency) never echoes a change back
// before the NEXT keystroke fires, so the input keeps resetting to the
// stale last-confirmed value between keystrokes instead of accumulating
// what the user is typing. A small local draft, reset only when the
// confirmed value changes to something the draft doesn't already reflect
// (the same pattern OllamaTaskField/ApiProviderPage already use), fixes it.
//
// Adversarial-review finding, deliberately NOT further chased: this reset
// compares the incoming value only against the last value WE'VE SEEN, not
// against every edit we've SENT - so a same-session echo of an EARLIER
// keystroke landing after a NEWER one would still stomp the newer draft.
// A fully correct fix needs echo-cancellation (a pending-edit counter) or a
// backend-tracked version stamp; both add real state-machine complexity
// for a narrow window that requires sustained fast typing during a slow
// round trip on a loopback WS connection. This is the same class of
// already-accepted risk OllamaTaskField's own explicit-model-ID input has
// (no draft buffer at all there) - not a new regression, just not fully
// closed either.
function LlamaCppNumberField({
  label,
  value,
  min,
  max,
  step,
  placeholder,
  onCommit,
}: {
  label: string;
  value: number;
  min?: number;
  max?: number;
  step?: number;
  placeholder?: string;
  onCommit: (n: number) => void;
}) {
  const [draft, setDraft] = useState(String(value));
  const [lastValue, setLastValue] = useState(value);

  if (value !== lastValue) {
    setLastValue(value);
    setDraft(String(value));
  }

  return (
    <label className="settings-field">
      <span className="settings-field-label">{label}</span>
      <input
        type="number"
        className="settings-select"
        min={min}
        max={max}
        step={step}
        placeholder={placeholder}
        value={draft}
        onChange={(event) => {
          setDraft(event.target.value);
          const n = Number(event.target.value);
          if (!Number.isNaN(n) && event.target.value.trim() !== "") onCommit(n);
        }}
      />
    </label>
  );
}

function LlamaCppPage({ state, transport }: { state: AppSettingsState; transport: WsTransport }) {
  const [draftChatFormat, setDraftChatFormat] = useState(state.llamaCppChatFormat);
  const [lastChatFormat, setLastChatFormat] = useState(state.llamaCppChatFormat);

  if (state.llamaCppChatFormat !== lastChatFormat) {
    setLastChatFormat(state.llamaCppChatFormat);
    setDraftChatFormat(state.llamaCppChatFormat);
  }

  // Chat/title model path fields are STAGED server-side (backend/settings.py's
  // llama_staged_chat_path/llama_staged_title_path) - Browse/select updates
  // the draft immediately (visible via state), but nothing persists until
  // Save Settings, matching the API-provider page's own draft-then-commit
  // shape rather than Ollama's per-field immediate persist.
  const scannedChatValue = state.llamaCppScannedModels.includes(state.llamaCppChatModelPath)
    ? state.llamaCppChatModelPath
    : "";
  const scannedTitleValue = state.llamaCppScannedModels.includes(state.llamaCppTitleModelPath)
    ? state.llamaCppTitleModelPath
    : "";

  return (
    <div className="settings-general-page">
      {/* Compares against the PERSISTED Llama.cpp config, same as
          apply_provider_mode's own Llama.cpp branch reads
          (settings_manager.get_llama_cpp_settings()) - if the model path
          fields below have unsaved edits, switching here still activates
          the last-saved config, not the draft on screen. Save Settings
          first to switch to what you just typed. */}
      <ProviderModeSwitch mode={MODE_LLAMACPP_LOCAL} state={state} transport={transport} />

      <fieldset className="settings-fieldset">
        <legend>Reasoning Level</legend>
        {REASONING_LEVEL_OPTIONS.map((option) => (
          <label className="settings-checkbox-row" key={option.id}>
            <input
              type="radio"
              name="llama-cpp-reasoning-level"
              checked={state.llamaCppReasoningLevel === option.id}
              onChange={() => transport.fireIntent("app-settings", "setLlamaCppReasoningLevel", [option.id], undefined, true)}
            />
            {option.label}
          </label>
        ))}
      </fieldset>

      <p className="settings-update-status">
        Current Active GGUF: <strong>{state.llamaCppChatModelPath ? basename(state.llamaCppChatModelPath) : "No model selected"}</strong>
      </p>

      <div className="settings-button-row">
        <button
          type="button"
          className="settings-button"
          disabled={state.llamaCppScanStatus === "running"}
          onClick={() => transport.fireIntent("app-settings", "scanLlamaCppSystem", [])}
        >
          {state.llamaCppScanStatus === "running" ? "Scanning..." : "System Scan"}
        </button>
        <button
          type="button"
          className="settings-button"
          disabled={state.llamaCppScanStatus === "running"}
          onClick={() => transport.fireIntent("app-settings", "pickLlamaCppScanFolder", [])}
        >
          Scan Folder...
        </button>
      </div>
      <p className="settings-update-status">{state.llamaCppScanSummary}</p>

      <datalist id={LLAMA_CPP_MODELS_DATALIST_ID}>
        {state.llamaCppScannedModels.map((path) => (
          <option key={path} value={path} />
        ))}
      </datalist>

      {state.llamaCppScannedModels.length > 0 && (
        <div className="settings-field">
          <span className="settings-field-label">Scanned Chat Model</span>
          <CustomSelect
            ariaLabel="Scanned Chat Model"
            value={scannedChatValue}
            options={[
              { id: "", label: "Select a scanned model..." },
              ...state.llamaCppScannedModels.map((path) => ({ id: path, label: basename(path) })),
            ]}
            onChange={(path) => transport.fireIntent("app-settings", "setLlamaCppChatModelPath", [path], undefined, true)}
          />
        </div>
      )}

      <div className="settings-field">
        <span className="settings-field-label">Chat Model File</span>
        <span className="settings-update-status">{state.llamaCppChatModelPath || "No file selected"}</span>
        <button
          type="button"
          className="settings-button"
          onClick={() => transport.fireIntent("app-settings", "pickLlamaCppChatModelFile", [])}
        >
          Browse...
        </button>
      </div>

      {state.llamaCppScannedModels.length > 0 && (
        <div className="settings-field">
          <span className="settings-field-label">Scanned Naming Model</span>
          <CustomSelect
            ariaLabel="Scanned Naming Model"
            value={scannedTitleValue}
            options={[
              { id: "", label: "Select a scanned model..." },
              ...state.llamaCppScannedModels.map((path) => ({ id: path, label: basename(path) })),
            ]}
            onChange={(path) => transport.fireIntent("app-settings", "setLlamaCppTitleModelPath", [path], undefined, true)}
          />
        </div>
      )}

      <div className="settings-field">
        <span className="settings-field-label">Chat Naming File (optional)</span>
        <span className="settings-update-status">{state.llamaCppTitleModelPath || "Reusing the main chat model"}</span>
        <button
          type="button"
          className="settings-button"
          onClick={() => transport.fireIntent("app-settings", "pickLlamaCppTitleModelFile", [])}
        >
          Browse...
        </button>
      </div>

      <label className="settings-field">
        <span className="settings-field-label">Chat Format Override</span>
        <input
          type="text"
          className="settings-select"
          placeholder="Leave blank to let the GGUF metadata decide"
          value={draftChatFormat}
          onChange={(event) => {
            setDraftChatFormat(event.target.value);
            transport.fireIntent("app-settings", "setLlamaCppChatFormat", [event.target.value], undefined, true);
          }}
        />
      </label>

      <LlamaCppNumberField
        label="Context Window"
        value={state.llamaCppNCtx}
        min={256}
        max={131072}
        step={256}
        onCommit={(n) => transport.fireIntent("app-settings", "setLlamaCppNCtx", [n], undefined, true)}
      />
      <LlamaCppNumberField
        label="GPU Layers"
        value={state.llamaCppNGpuLayers}
        min={-1}
        max={9999}
        onCommit={(n) => transport.fireIntent("app-settings", "setLlamaCppNGpuLayers", [n], undefined, true)}
      />
      <LlamaCppNumberField
        label="CPU Threads"
        value={state.llamaCppNThreads}
        min={0}
        max={256}
        placeholder="0 = Auto"
        onCommit={(n) => transport.fireIntent("app-settings", "setLlamaCppNThreads", [n], undefined, true)}
      />

      {state.llamaCppNotice && (
        <p className="settings-update-status" data-level="error">
          {state.llamaCppNotice}
        </p>
      )}

      <div className="settings-button-row">
        <button
          type="button"
          className="settings-button settings-button-primary"
          onClick={() => transport.fireIntent("app-settings", "saveLlamaCppSettings", [])}
        >
          Save Settings
        </button>
      </div>
    </div>
  );
}

// ADR-012 stage 12.6: the deferred UI half of ADR-007 stage 7.5's MCP client
// - an McpServerConfig dataclass and SettingsManager.get_mcp_servers/
// set_mcp_servers persistence already existed (backend/mcp_client.py, its
// own module docstring explicitly deferred this page to ADR-012) with zero
// way to view or edit the configured list until now. Every mutation below
// sends the FULL updated array via setMcpServers - bulk-replace, matching
// SettingsManager.set_mcp_servers' own "replace the whole collection"
// posture, the simplest shape to implement and test on both the toggle/
// remove path (derived from the current state.mcpServers) and the add path
// (state.mcpServers plus one new entry). queueable (same as GeneralPage's
// checkboxes/OllamaTaskField's selects above) - a pure persisted setting
// with no live side effect at save time (backend/agents.py's
// _register_configured_mcp_tools only connects enabled servers lazily, when
// the Builder registry is next built), so replaying it after a reconnect is
// always safe.
/** "KEY=value" lines -> env record. Blank lines and lines without "=" are
 * skipped; the first "=" splits, so a value may itself contain "=" (base64
 * tokens routinely do). Exported for direct unit testing. */
export function parseEnvLines(text: string): Record<string, string> {
  const env: Record<string, string> = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    if (!key) continue;
    env[key] = line.slice(eq + 1).trim();
  }
  return env;
}

function McpServersPage({ state, transport }: { state: AppSettingsState; transport: WsTransport }) {
  const [draftName, setDraftName] = useState("");
  const [draftCommand, setDraftCommand] = useState("");
  const [draftArgs, setDraftArgs] = useState("");
  const [draftEnv, setDraftEnv] = useState("");

  // What setMcpServers SENDS, which is genuinely not the same shape the
  // app-settings state carries back. env values are write-only on this wire
  // (see the contract's own McpServerConfigPayload.envKeys): the state we
  // render has names only, while an outgoing entry MAY carry real values
  // when the user just typed them. A missing `env` means "keep whatever is
  // stored for this server", which is what lets toggling or removing one
  // server leave every other server's variables untouched.
  //
  // Spelled out in full rather than written as `McpServerConfig & { env?: }`
  // deliberately: intersecting a generated wire type is the ADR-003 C9
  // anti-pattern (see lib/bridge-core/wireTypeCastGuard.test.ts) - it tells
  // TypeScript a wire field exists on the author's word. This type describes
  // the OUTBOUND intent argument, which the generated inbound row type has
  // no business defining.
  type OutgoingMcpServer = {
    name: string;
    command: string;
    args: string[];
    scopes: string[];
    approval: string;
    enabledTools: string[];
    enabled: boolean;
    timeout: number;
    envKeys: string[];
    env?: Record<string, string>;
  };

  const updateServers = (next: OutgoingMcpServer[]) => {
    transport.fireIntent("app-settings", "setMcpServers", [next], undefined, true);
  };

  const handleAdd = () => {
    const name = draftName.trim();
    const command = draftCommand.trim();
    if (!name || !command) return;
    const args = draftArgs.trim() ? draftArgs.trim().split(/\s+/) : [];
    const env = parseEnvLines(draftEnv);
    updateServers([
      ...state.mcpServers,
      {
        name, command, args, scopes: [], approval: "always", enabledTools: [], enabled: true, timeout: 30,
        // The one place values are sent: the user just typed them. envKeys
        // keeps the entry the same shape the rest of the list has.
        envKeys: Object.keys(env).sort(),
        env,
      },
    ]);
    setDraftName("");
    setDraftCommand("");
    setDraftArgs("");
    setDraftEnv("");
  };

  return (
    <div className="settings-general-page">
      <p className="settings-integrations-intro">
        Configure local MCP (Model Context Protocol) servers. Each enabled server's tools become available to the
        Builder, namespaced and approval-gated - MCP servers run arbitrary user-configured commands, so treat them
        the same as any other third-party code you choose to run.
      </p>

      <fieldset className="settings-fieldset">
        <legend>Configured Servers</legend>
        {state.mcpServers.length === 0 && (
          <p className="settings-update-status">No MCP servers configured yet.</p>
        )}
        {state.mcpServers.map((server, index) => (
          <div className="settings-mcp-server-row" key={`${server.name}-${index}`}>
            <label
              className="settings-checkbox-row settings-mcp-server-toggle"
              aria-label={server.name || "MCP server"}
            >
              <input
                type="checkbox"
                checked={server.enabled}
                onChange={(event) =>
                  updateServers(
                    state.mcpServers.map((s, i) => (i === index ? { ...s, enabled: event.target.checked } : s)),
                  )
                }
              />
              <span className="settings-mcp-server-info">
                <span className="settings-mcp-server-name">{server.name}</span>
                <span className="settings-mcp-server-command">
                  {server.command}
                  {server.args.length > 0 ? ` ${server.args.join(" ")}` : ""}
                </span>
                {/* Names only, never values - these are the user's own
                    tokens for a server they chose to run, and a settings
                    page is no place to echo a secret back. */}
                {(server.envKeys ?? []).length > 0 && (
                  <span className="settings-mcp-server-command">
                    env: {[...server.envKeys].sort().join(", ")}
                  </span>
                )}
              </span>
            </label>
            <button
              type="button"
              className="settings-button settings-mcp-server-remove"
              aria-label={`Remove ${server.name}`}
              onClick={() => updateServers(state.mcpServers.filter((_, i) => i !== index))}
            >
              Remove
            </button>
          </div>
        ))}
      </fieldset>

      <fieldset className="settings-fieldset">
        <legend>Add Server</legend>
        <label className="settings-field">
          <span className="settings-field-label">Server Name</span>
          <input
            type="text"
            className="settings-select"
            placeholder="e.g. filesystem"
            value={draftName}
            onChange={(event) => setDraftName(event.target.value)}
          />
        </label>
        <label className="settings-field">
          <span className="settings-field-label">Command</span>
          <input
            type="text"
            className="settings-select"
            placeholder="e.g. npx"
            value={draftCommand}
            onChange={(event) => setDraftCommand(event.target.value)}
          />
        </label>
        <label className="settings-field">
          <span className="settings-field-label">Arguments (optional, space-separated)</span>
          <input
            type="text"
            className="settings-select"
            placeholder="-y @modelcontextprotocol/server-filesystem /path/to/allow"
            value={draftArgs}
            onChange={(event) => setDraftArgs(event.target.value)}
          />
        </label>
        <label className="settings-field">
          <span className="settings-field-label">Environment variables (optional, one KEY=value per line)</span>
          <textarea
            className="settings-select settings-mcp-env-input"
            rows={3}
            placeholder={"GITHUB_TOKEN=ghp_...\nBRAVE_API_KEY=..."}
            value={draftEnv}
            onChange={(event) => setDraftEnv(event.target.value)}
            spellCheck={false}
          />
          <span className="settings-field-hint">
            A server receives only these variables plus basic system plumbing (PATH, TEMP, HOME) - never this
            app&apos;s own provider keys.
          </span>
        </label>
        <div className="settings-button-row">
          <button
            type="button"
            className="settings-button settings-button-primary"
            disabled={!draftName.trim() || !draftCommand.trim()}
            onClick={handleAdd}
          >
            Add Server
          </button>
        </div>
      </fieldset>
    </div>
  );
}

// ADR-014 stage 14.4: install-time consent for discovered THIRD-PARTY
// plugins, mirroring McpServersPage's own minimalism immediately above -
// one row per entry, a single checkbox, no per-scope editing UI (MCP
// Servers itself has never had one for its own `scopes` field, so this
// stays exactly that coarse). Built-in plugins (the 8 migrated in stage
// 14.3) never appear in `grants` - backend/plugins.py only emits an entry
// per distinct plugin_id reached through the generic, non-builtin_actions
// discovery path - so this page can never gate anything that ships with
// the app itself.
//
// Honesty note (carried over from the ADR-014 stage 14.4 design): checking
// "Granted" here answers "did the user consent to this plugin acting at
// all," not "is this specific mutation confined to some enforced boundary."
// A plugin's declared scopes are a self-reported checklist the backend
// records for its own self-documentation, not a sandboxed capability set -
// real capability sandboxing is ADR-014 stage 14.5's job (out-of-process
// execution). This page does not claim otherwise.
function PluginsPage({ grants, transport }: { grants: AppPluginGrant[]; transport: WsTransport }) {
  return (
    <div className="settings-general-page">
      <p className="settings-integrations-intro">
        Discovered third-party plugins are not granted by default. A plugin listed here cannot create nodes or run
        its intents until you check "Granted" for it - built-in plugins ship with the app and are never listed or
        gated here.
      </p>

      <fieldset className="settings-fieldset">
        <legend>Discovered Plugins</legend>
        {grants.length === 0 && (
          <p className="settings-update-status">No third-party plugins need a grant right now.</p>
        )}
        {grants.map((grant) => (
          <div className="settings-mcp-server-row" key={grant.pluginId}>
            <label className="settings-checkbox-row settings-mcp-server-toggle">
              <input
                type="checkbox"
                aria-label={`Granted: ${grant.name}`}
                checked={grant.granted}
                onChange={(event) =>
                  transport.fireIntent(
                    "app-plugins",
                    "setPluginGrant",
                    [grant.pluginId, event.target.checked],
                    undefined,
                    true,
                  )
                }
              />
              <span className="settings-mcp-server-info">
                <span className="settings-mcp-server-name">{grant.name}</span>
                <span className="settings-mcp-server-command">
                  {grant.scopes.length > 0 ? grant.scopes.join(", ") : "No declared scopes"}
                </span>
              </span>
            </label>
          </div>
        ))}
      </fieldset>
    </div>
  );
}

// ADR-012 stage 12.6: a read-only disclosure surface, not a settings page in
// the usual sense - there is nothing here to edit (per ADR-005 §4, these
// caps are a fixed, backend-computed fact, not a user-tunable preference),
// so unlike every other page in this file there is no transport prop and no
// fireIntent call anywhere below. Sourced from useExecutionLimits()
// (ExecutionLimitsContext.tsx) - the SAME context CodeExecutionApprovalPanel.tsx
// already reads before a human approves a pending Py-Coder/Code-Sandbox run -
// rather than a second copy of the strings, so this page and that panel can
// never drift out of sync with each other or with the backend's own
// platform-conditional computation (backend/execution_limits.py). Exists so
// the disclosure is reachable on its own, ahead of time, rather than only
// surfacing the first time a user is mid-approval and already under time
// pressure to decide.
function ResourceLimitsPage() {
  const executionLimits = useExecutionLimits();
  const hasAnyText = !!executionLimits.pycoderResourceLimitsText || !!executionLimits.codeSandboxResourceLimitsText;

  return (
    <div className="settings-general-page">
      <p className="settings-integrations-intro">
        The resource caps applied to AI-driven code execution, computed by the backend for this system. The same
        text is shown in the Py-Coder / Virtual Environment Runner approval prompt before you approve a run -
        this page just makes it reachable without waiting for one.
      </p>

      {!!executionLimits.pycoderResourceLimitsText && (
        <div className="settings-field">
          <span className="settings-field-label">Py-Coder</span>
          <p className="settings-update-status">{executionLimits.pycoderResourceLimitsText}</p>
        </div>
      )}

      {!!executionLimits.codeSandboxResourceLimitsText && (
        <div className="settings-field">
          <span className="settings-field-label">Virtual Environment Runner</span>
          <p className="settings-update-status">{executionLimits.codeSandboxResourceLimitsText}</p>
        </div>
      )}

      {!hasAnyText && (
        <p className="settings-update-status">No resource limits have been reported by the backend yet.</p>
      )}
    </div>
  );
}

export function SettingsDialog({ transport }: { transport: WsTransport }) {
  const [state, setState] = useState<AppSettingsState>(initialState);
  // ADR-014 stage 14.4: a second, independent subscription to "app-plugins"
  // (the same topic PluginPicker.tsx already reads) - the grants list isn't
  // part of "app-settings" (which this dialog otherwise reads exclusively),
  // so this is a sibling subscription, not a repurposing of `state` above.
  const [pluginsState, setPluginsState] = useState<AppPluginsState>(initialPluginsState);

  useEffect(() => {
    return transport.subscribe("app-settings", (payload) => {
      const validated = TOPIC_VALIDATORS["app-settings"](payload);
      if (validated.ok) setState(validated.value as AppSettingsState);
      else console.error("[app-settings] rejected snapshot:", validated.errors);
    });
  }, [transport]);

  useEffect(() => {
    return transport.subscribe("app-plugins", (payload) => {
      const validated = TOPIC_VALIDATORS["app-plugins"](payload);
      if (validated.ok) setPluginsState(validated.value as AppPluginsState);
      else console.error("[app-plugins] rejected snapshot:", validated.errors);
    });
  }, [transport]);

  const activeSection = (SECTIONS.find((s) => sectionKey(s) === state.activeSection) ?? "General") as Section;

  return (
    <Dialog name="settings" title="Settings" className="settings-dialog">
      {/* ADR-004 stage 4.4: persistent (visible regardless of which
          section tab is active, not a one-time toast) - a DPAPI failure
          means every API key/GitHub token this dialog saves from now on
          is written to disk in PLAINTEXT, a fact worth surfacing no
          matter which page a user happens to be on when it's true. Hidden
          entirely in the common case (secretsEncryptedAtRest is true).
          role="alert" (adversarial-review fix) matches every other warning/
          error banner in this codebase (BridgeErrorState.tsx, the 3
          node-view banner-error divs) - without it, the dialog's own focus
          trap moves focus straight to the rail buttons on open (this <p>
          isn't focusable), so screen-reader users could tab straight past
          this security-relevant text and never encounter it, and a later
          flip from encrypted to unencrypted while the dialog is already
          open would render with no assistive-tech announcement at all. */}
      {!state.secretsEncryptedAtRest && (
        <p className="settings-update-status settings-secrets-warning" data-level="warning" role="alert">
          API keys are stored unencrypted on this system (Windows DPAPI is unavailable or failing here).
        </p>
      )}
      <div className="settings-shell">
        <nav className="settings-rail" aria-label="Settings sections">
          {SECTIONS.map((section) => (
            <button
              key={section}
              type="button"
              className={"settings-rail-button" + (section === activeSection ? " active" : "")}
              aria-current={section === activeSection ? "page" : undefined}
              onClick={() => transport.fireIntent("app-settings", "setActiveSection", [sectionKey(section)], undefined, true)}
            >
              {section}
            </button>
          ))}
        </nav>
        <div className="settings-page" role="region" aria-label={activeSection}>
          {activeSection === "General" ? (
            <GeneralPage state={state} transport={transport} />
          ) : activeSection === "Integrations" ? (
            <IntegrationsPage state={state} transport={transport} />
          ) : activeSection === "API Endpoint" ? (
            <ApiProviderPage state={state} transport={transport} />
          ) : activeSection === "Ollama (Local)" ? (
            <OllamaPage state={state} transport={transport} />
          ) : activeSection === "Llama.cpp (Local)" ? (
            <LlamaCppPage state={state} transport={transport} />
          ) : activeSection === "MCP Servers" ? (
            <McpServersPage state={state} transport={transport} />
          ) : activeSection === "Plugins" ? (
            <PluginsPage grants={pluginsState.grants} transport={transport} />
          ) : activeSection === "Resource Limits" ? (
            <ResourceLimitsPage />
          ) : (
            activeSection
          )}
        </div>
      </div>
    </Dialog>
  );
}
