import { useEffect, useState } from "react";
import type { WsTransport } from "../../lib/ws/transport";
import { TOPIC_VALIDATORS } from "../../lib/api-contract/topics";
import type { AppSettingsState } from "../../lib/bridge-core/generated/app-settings-state";
import { Dialog } from "../overlays/overlays";
import { CustomSelect } from "./CustomSelect";

/**
 * The settings dialog (Qt-removal plan R2.5d, extended R7.4a-c) - settings
 * island's SPA successor. Every page R2.5d originally deferred is real now:
 * General, Integrations, API-provider, Ollama, and (R7.4c) Llama.cpp. The
 * Ollama page's own "Scan Folder..." button, deferred alongside Llama.cpp
 * pending a native folder-picker capability, is real too - see
 * backend/native_dialogs.py's docstring for the mechanism.
 */

const SECTIONS = ["General", "Ollama (Local)", "Llama.cpp (Local)", "API Endpoint", "Integrations"] as const;
type Section = (typeof SECTIONS)[number];

// Mirrors graphlink_task_config.py's TASK_* constants - the same 5-slot set
// backend/settings.py's _OLLAMA_TASK_KEYS uses (task_image_gen is absent:
// Ollama has no image-generation path).
const OLLAMA_TASKS = ["task_chat", "task_title", "task_chart", "task_web_validate", "task_web_summarize"] as const;
const OLLAMA_TASK_LABELS: Record<(typeof OLLAMA_TASKS)[number], string> = {
  task_chat: "Chat Model",
  task_title: "Chat Naming Model",
  task_chart: "Chart Generation Model",
  task_web_validate: "Web Content Validation Model",
  task_web_summarize: "Web Content Summarization Model",
};
const OLLAMA_MODELS_DATALIST_ID = "settings-ollama-scanned-models";
const LLAMA_CPP_MODELS_DATALIST_ID = "settings-llama-cpp-scanned-models";

// R8a: reasoning went from a 2-value Mode (Thinking/Quick) to a graded
// 4-value Level shared by both local providers here and the composer's own
// Reasoning popover (backend/composer.py's REASONING_OPTIONS) - same ids,
// same labels, so a user never has to learn two different vocabularies.
const REASONING_LEVEL_OPTIONS = [
  { id: "off", label: "Off" },
  { id: "low", label: "Low" },
  { id: "medium", label: "Medium" },
  { id: "high", label: "High" },
] as const;

// Llama.cpp has no per-task assignment concept like Ollama's OLLAMA_TASKS -
// just one global chat model path plus an optional title/naming override
// (api_provider.py's _get_llama_cpp_model_path: chart/web-validate/web-
// summarize all silently fall back to the chat model path).
function basename(path: string): string {
  return path.split(/[\\/]/).pop() || path;
}

const NOTIFICATION_TYPE_LABELS: Record<string, string> = {
  info: "Info",
  success: "Success",
  warning: "Warning",
  error: "Error",
};

// Mirrors graphlink_task_config.py's API_PROVIDER_* constants exactly (the
// wire values backend/settings.py's SettingsManager persists) - not an enum
// generated by codegen since these 3 strings are the whole of a small,
// stable, hand-maintained set, the same convention SECTIONS above follows.
const API_PROVIDER_OPENAI = "OpenAI-Compatible";
const API_PROVIDER_ANTHROPIC = "Anthropic Claude";
const API_PROVIDER_GEMINI = "Google Gemini";
const API_PROVIDERS = [API_PROVIDER_OPENAI, API_PROVIDER_ANTHROPIC, API_PROVIDER_GEMINI] as const;
// Mirrors SettingsManager.get_api_base_url()'s own default (graphlink_settings_store.py).
const DEFAULT_OPENAI_BASE_URL = "https://api.openai.com/v1";

// Mirrors graphlink_task_config.py's TASK_* constants exactly.
const TASK_TITLE = "task_title";
const TASK_CHAT = "task_chat";
const TASK_CHART = "task_chart";
const TASK_IMAGE_GEN = "task_image_gen";
const TASK_WEB_VALIDATE = "task_web_validate";
const TASK_WEB_SUMMARIZE = "task_web_summarize";

const API_TASK_FIELDS: { task: string; label: string }[] = [
  { task: TASK_TITLE, label: "Chat Naming / Session Title" },
  { task: TASK_CHAT, label: "Chat, Explain, Takeaways (main model)" },
  { task: TASK_CHART, label: "Chart Generation (code-capable model)" },
  { task: TASK_IMAGE_GEN, label: "Image Generation" },
  { task: TASK_WEB_VALIDATE, label: "Web Content Validation" },
  { task: TASK_WEB_SUMMARIZE, label: "Web Content Summarization" },
];

const initialState: AppSettingsState = {
  schemaVersion: 1,
  minCompatibleSchemaVersion: 1,
  revision: 0,
  activeSection: "General",
  showTokenCounter: true,
  enableSystemPrompt: true,
  notificationPreferences: {},
  githubTokenConfigured: false,
  // ADR-004 stage 4.4: optimistic default (true = encrypted) so the
  // persistent badge below never flashes a false warning before the
  // first real snapshot arrives - the real backend value replaces this
  // on the very first "app-settings" publish, same as every other field
  // here.
  secretsEncryptedAtRest: true,
  activeApiProvider: API_PROVIDER_OPENAI,
  viewingApiProvider: API_PROVIDER_OPENAI,
  apiBaseUrl: DEFAULT_OPENAI_BASE_URL,
  apiKeyConfigured: { openai: false, anthropic: false, gemini: false },
  apiKeySource: { openai: "none", anthropic: "none", gemini: "none" },
  apiModels: {},
  apiModelCatalog: [],
  apiCatalogStatus: "idle",
  apiCatalogMessage: "Model catalog has not been refreshed yet.",
  geminiStaticModels: [],
  geminiStaticImageModels: [],
  ollamaReasoningLevel: "high",
  ollamaCurrentModel: "",
  ollamaModelAssignments: {},
  ollamaScannedModels: [],
  ollamaScanSummary: "",
  ollamaScanStatus: "idle",
  ollamaPullStatus: "idle",
  ollamaNotice: "",
  llamaCppReasoningLevel: "high",
  llamaCppChatModelPath: "",
  llamaCppTitleModelPath: "",
  llamaCppChatFormat: "",
  llamaCppNCtx: 4096,
  llamaCppNGpuLayers: 0,
  llamaCppNThreads: 0,
  llamaCppScannedModels: [],
  llamaCppScanSummary: "",
  llamaCppScanStatus: "idle",
  llamaCppNotice: "",
};

function sectionKey(section: Section): string {
  // Backend storage is UI-navigation-only for this field (mirrors the
  // legacy bridge - see backend/settings.py's active_section cell), so any
  // stable string works; reusing the display name keeps the wire traffic
  // human-readable in the WS inspector.
  return section === "General" ? "general" : section === "Integrations" ? "integrations" : section.toLowerCase();
}

function GeneralPage({
  state,
  transport,
}: {
  state: AppSettingsState;
  transport: WsTransport;
}) {
  // R8a (UI/UX issue list finding #9): a Theme select (Dark/Muted/
  // Monochromatic) used to live here. It persisted a real setTheme intent,
  // but nothing in the SPA ever applied the value - no data-theme attribute,
  // no alternate token set, the app rendered identically no matter what was
  // selected. Removed rather than wired up: building two real alternate
  // palettes is a design decision, not a bug fix, and a persisted preference
  // that provably does nothing is worse than no preference at all.
  return (
    <div className="settings-general-page">
      <label className="settings-checkbox-row">
        <input
          type="checkbox"
          checked={state.showTokenCounter}
          onChange={(event) => transport.fireIntent("app-settings", "setShowTokenCounter", [event.target.checked])}
        />
        Show Token Counter Overlay
      </label>

      <label className="settings-checkbox-row">
        <input
          type="checkbox"
          checked={state.enableSystemPrompt}
          onChange={(event) => transport.fireIntent("app-settings", "setEnableSystemPrompt", [event.target.checked])}
        />
        Enable Assistant System Prompt
      </label>

      <fieldset className="settings-fieldset">
        <legend>Notification types</legend>
        {Object.keys(NOTIFICATION_TYPE_LABELS).map((type) => (
          <label className="settings-checkbox-row" key={type}>
            <input
              type="checkbox"
              checked={state.notificationPreferences[type] ?? true}
              onChange={(event) =>
                transport.fireIntent("app-settings", "setNotificationPreference", [type, event.target.checked])
              }
            />
            {NOTIFICATION_TYPE_LABELS[type]}
          </label>
        ))}
      </fieldset>
    </div>
  );
}

function IntegrationsPage({
  state,
  transport,
}: {
  state: AppSettingsState;
  transport: WsTransport;
}) {
  const [draftToken, setDraftToken] = useState("");

  return (
    <div className="settings-general-page">
      <p className="settings-integrations-intro">
        Store optional external-service tokens used by specialized plugins. The Gitlink plugin uses a GitHub
        personal access token to load your private repositories - if you leave this empty, it still works with
        public repositories.
      </p>

      <label className="settings-field">
        <span className="settings-field-label">GitHub Personal Access Token</span>
        <input
          type="password"
          className="settings-select"
          placeholder="ghp_... or fine-grained token"
          value={draftToken}
          onChange={(event) => setDraftToken(event.target.value)}
        />
      </label>

      <p className="settings-update-status">
        {state.githubTokenConfigured ? "A GitHub token is currently configured." : "No GitHub token configured."}
      </p>

      <div className="settings-button-row">
        <button
          type="button"
          className="settings-button"
          onClick={() => {
            transport.fireIntent("app-settings", "clearGithubToken", []);
            setDraftToken("");
          }}
        >
          Clear Token
        </button>
        <button
          type="button"
          className="settings-button settings-button-primary"
          disabled={draftToken.trim().length === 0}
          onClick={() => {
            transport.fireIntent("app-settings", "setGithubToken", [draftToken]);
            setDraftToken("");
          }}
        >
          Save Integrations
        </button>
      </div>
    </div>
  );
}

function ApiProviderPage({
  state,
  transport,
}: {
  state: AppSettingsState;
  transport: WsTransport;
}) {
  const viewingProvider = state.viewingApiProvider;
  const isOpenAi = viewingProvider === API_PROVIDER_OPENAI;
  const isAnthropic = viewingProvider === API_PROVIDER_ANTHROPIC;

  // Draft fields, not server state - mirrors IntegrationsPage's draftToken:
  // the key is write-only (never pre-filled from state, unlike the legacy
  // QWidget - see this file's module docstring for why), and base
  // URL/per-task models are a local edit buffer until Save commits them.
  // Re-synced from the server snapshot whenever the VIEWED provider changes,
  // matching the legacy dialog's own per-provider field reset. Uses React's
  // "adjusting state when a prop changes" pattern (comparing against a
  // tracked previous value INSIDE render, not a useEffect) so a genuine
  // provider switch resets the drafts in the same render/commit rather than
  // flashing the old provider's stale draft for one extra frame first.
  const [draftApiKey, setDraftApiKey] = useState("");
  const [draftBaseUrl, setDraftBaseUrl] = useState(state.apiBaseUrl);
  const [draftModels, setDraftModels] = useState<Record<string, string>>(state.apiModels);
  const [confirmingReset, setConfirmingReset] = useState(false);
  const [lastViewingProvider, setLastViewingProvider] = useState(viewingProvider);

  if (viewingProvider !== lastViewingProvider) {
    setLastViewingProvider(viewingProvider);
    setDraftApiKey("");
    setDraftBaseUrl(state.apiBaseUrl);
    setDraftModels(state.apiModels);
    // Don't leave a Reset armed across a provider switch.
    setConfirmingReset(false);
  }

  const catalogModelIds = state.apiModelCatalog.map((entry) => entry.modelId);
  const modelOptionsFor = (task: string): string[] => {
    if (isOpenAi || isAnthropic) return catalogModelIds;
    return task === TASK_IMAGE_GEN ? state.geminiStaticImageModels : state.geminiStaticModels;
  };

  const requiredTasks = API_TASK_FIELDS.filter(({ task }) => !(isAnthropic && task === TASK_IMAGE_GEN));
  // ADR-004 stage 4.4: the same provider-key derivation apiKeyConfigured's
  // placeholder below already needed, factored out so apiKeySource's new
  // "provided by environment" hint reads the identical key - one place
  // deciding "which of the 3 wire dicts' entries describes the viewed
  // provider", not two that could silently diverge.
  const viewingProviderKey = isOpenAi ? "openai" : isAnthropic ? "anthropic" : "gemini";

  return (
    <div className="settings-general-page">
      <div className="settings-field">
        <span className="settings-field-label">API Provider</span>
        <CustomSelect
          ariaLabel="API Provider"
          value={viewingProvider}
          options={API_PROVIDERS.map((provider) => ({ id: provider, label: provider }))}
          onChange={(id) => transport.fireIntent("app-settings", "setViewingApiProvider", [id])}
        />
      </div>

      <p className="settings-update-status">
        {viewingProvider === state.activeApiProvider
          ? `${state.activeApiProvider} is the currently active provider.`
          : `Currently active: ${state.activeApiProvider}. Save to switch to ${viewingProvider}.`}
      </p>

      {isOpenAi && (
        <label className="settings-field">
          <span className="settings-field-label">Base URL</span>
          <input
            type="text"
            className="settings-select"
            placeholder="https://api.openai.com/v1"
            value={draftBaseUrl}
            onChange={(event) => setDraftBaseUrl(event.target.value)}
          />
        </label>
      )}

      <label className="settings-field">
        <span className="settings-field-label">API Key</span>
        <input
          type="password"
          className="settings-select"
          placeholder={
            (state.apiKeyConfigured as Record<string, boolean>)[viewingProviderKey]
              ? "A key is configured - enter a new one to replace it"
              : "Enter your API key..."
          }
          value={draftApiKey}
          onChange={(event) => setDraftApiKey(event.target.value)}
        />
        {/* ADR-004 stage 4.4: surfaces api_provider.py's own env-var key
            fallback, previously invisible. apiKeySource[viewingProviderKey]
            reflects the VIEWED provider (per its own dropdown), which may
            not be the ACTIVE one - so this is a prediction ("if you saved/
            activated this provider, its key would come from the
            environment"), not a claim that the environment is supplying a
            key to a live request right now. "stored" whenever a saved key
            already exists (a stored key always wins over the environment -
            see backend/settings.py's own _api_key_source). Saving a key
            here will switch this to "stored" on the next snapshot, same as
            apiKeyConfigured already does. */}
        {(state.apiKeySource as Record<string, string>)[viewingProviderKey] === "environment" && (
          <span className="settings-field-hint">
            Key provided by an environment variable, not Settings.
          </span>
        )}
      </label>

      {(isOpenAi || isAnthropic) && (
        <>
          <div className="settings-button-row">
            <button
              type="button"
              className="settings-button"
              disabled={state.apiCatalogStatus === "loading"}
              onClick={() =>
                transport.fireIntent("app-settings", "loadApiModels", [viewingProvider, draftApiKey, draftBaseUrl])
              }
            >
              {state.apiCatalogStatus === "loading" ? "Loading catalog…" : "Load Available Models"}
            </button>
          </div>
          <p
            className="settings-update-status"
            data-level={state.apiCatalogStatus === "error" ? "warning" : undefined}
          >
            {state.apiCatalogMessage}
          </p>
        </>
      )}

      <fieldset className="settings-fieldset">
        <legend>Model Selection (per task)</legend>
        {API_TASK_FIELDS.filter(({ task }) => !(isAnthropic && task === TASK_IMAGE_GEN)).map(({ task, label }) => (
          <label className="settings-field" key={task}>
            <span className="settings-field-label">{label}</span>
            <input
              type="text"
              className="settings-select"
              list={`api-model-options-${task}`}
              placeholder="Select or type a model..."
              value={draftModels[task] ?? ""}
              onChange={(event) => setDraftModels((prev) => ({ ...prev, [task]: event.target.value }))}
            />
            <datalist id={`api-model-options-${task}`}>
              {modelOptionsFor(task).map((modelId) => (
                <option key={modelId} value={modelId} />
              ))}
            </datalist>
          </label>
        ))}
      </fieldset>

      {confirmingReset && (
        <p className="settings-update-status" data-level="error">
          This clears all saved API keys and model configurations and cannot be undone.
        </p>
      )}

      <div className="settings-button-row">
        {/* Reset wipes every provider's key irreversibly. Legacy gated it
            behind a "This cannot be undone" Yes/No prompt; this is the same
            two-step confirm the legacy settings island and ChatLibraryDialog
            already use, rather than a one-click destructive button. */}
        {confirmingReset ? (
          <>
            <button type="button" className="settings-button" onClick={() => setConfirmingReset(false)}>
              Cancel
            </button>
            <button
              type="button"
              className="settings-button settings-button-primary"
              onClick={() => {
                transport.fireIntent("app-settings", "resetApiSettings", []);
                // Reset must clear the local drafts too, not just the key:
                // the resync block only fires on a viewingProvider change,
                // which Reset doesn't cause, so stale draftBaseUrl/
                // draftModels would otherwise survive and a later Save
                // would re-persist exactly what Reset just cleared.
                setDraftApiKey("");
                setDraftBaseUrl(DEFAULT_OPENAI_BASE_URL);
                setDraftModels({});
                setConfirmingReset(false);
              }}
            >
              Confirm Reset
            </button>
          </>
        ) : (
          <button type="button" className="settings-button" onClick={() => setConfirmingReset(true)}>
            Reset API Settings
          </button>
        )}
        <button
          type="button"
          className="settings-button settings-button-primary"
          disabled={
            draftApiKey.trim().length === 0 ||
            requiredTasks.some(({ task }) => !(draftModels[task] ?? "").trim())
          }
          onClick={() => {
            transport.fireIntent("app-settings", "saveApiConfiguration", [
              viewingProvider,
              draftBaseUrl,
              draftApiKey,
              draftModels,
            ]);
            setDraftApiKey("");
          }}
        >
          Save Configuration
        </button>
      </div>
    </div>
  );
}

// The flat wire value ("inherit"|"auto"|"<explicit model id>") maps onto two
// UI controls: a mode select (mirrors the legacy island's 3 special combo
// entries) and a conditionally-shown text input for the explicit case. This
// is a deliberate 2-control simplification of the legacy single editable
// combo, ported verbatim from web_ui/src/islands/settings/App.tsx's own
// OllamaTaskField.
function OllamaTaskField({
  task,
  value,
  transport,
}: {
  task: (typeof OLLAMA_TASKS)[number];
  value: string;
  transport: WsTransport;
}) {
  const isSpecial = value === "inherit" || value === "auto";
  const [uiMode, setUiMode] = useState(isSpecial ? value : "explicit");
  const [prevValue, setPrevValue] = useState(value);

  if (value !== prevValue) {
    setPrevValue(value);
    setUiMode(isSpecial ? value : "explicit");
  }

  const modeOptions = [
    ...(task !== "task_chat" ? [{ id: "inherit", label: "Use chat model" }] : []),
    { id: "auto", label: "Auto - choose a compatible installed model" },
    { id: "explicit", label: "Custom model ID..." },
  ];

  return (
    <>
      <div className="settings-field">
        <span className="settings-field-label">{OLLAMA_TASK_LABELS[task]}</span>
        <CustomSelect
          ariaLabel={OLLAMA_TASK_LABELS[task]}
          value={uiMode}
          options={modeOptions}
          onChange={(nextMode) => {
            setUiMode(nextMode);
            if (nextMode !== "explicit") {
              transport.fireIntent("app-settings", "setOllamaModelAssignment", [task, nextMode]);
            }
          }}
        />
      </div>
      {uiMode === "explicit" && (
        <label className="settings-field">
          <span className="settings-field-label">{OLLAMA_TASK_LABELS[task]} (custom model ID)</span>
          <input
            type="text"
            className="settings-select"
            list={OLLAMA_MODELS_DATALIST_ID}
            value={isSpecial ? "" : value}
            onChange={(event) => transport.fireIntent("app-settings", "setOllamaModelAssignment", [task, event.target.value])}
          />
        </label>
      )}
    </>
  );
}

function OllamaPage({ state, transport }: { state: AppSettingsState; transport: WsTransport }) {
  const [draftPullModel, setDraftPullModel] = useState("");

  return (
    <div className="settings-general-page">
      <fieldset className="settings-fieldset">
        <legend>Reasoning Level</legend>
        {REASONING_LEVEL_OPTIONS.map((option) => (
          <label className="settings-checkbox-row" key={option.id}>
            <input
              type="radio"
              name="ollama-reasoning-level"
              checked={state.ollamaReasoningLevel === option.id}
              onChange={() => transport.fireIntent("app-settings", "setOllamaReasoningLevel", [option.id])}
            />
            {option.label}
          </label>
        ))}
      </fieldset>

      <p className="settings-update-status">
        Current Active Model: <strong>{state.ollamaCurrentModel || "Auto - no compatible installed model found"}</strong>
      </p>

      <div className="settings-button-row">
        <button
          type="button"
          className="settings-button"
          disabled={state.ollamaScanStatus === "running"}
          onClick={() => transport.fireIntent("app-settings", "scanOllamaSystem", [])}
        >
          {state.ollamaScanStatus === "running" ? "Scanning..." : "System Scan"}
        </button>
        <button
          type="button"
          className="settings-button"
          disabled={state.ollamaScanStatus === "running"}
          onClick={() => transport.fireIntent("app-settings", "pickOllamaScanFolder", [])}
        >
          Scan Folder...
        </button>
      </div>
      <p className="settings-update-status">{state.ollamaScanSummary}</p>

      <datalist id={OLLAMA_MODELS_DATALIST_ID}>
        {state.ollamaScannedModels.map((model) => (
          <option key={model} value={model} />
        ))}
      </datalist>

      <fieldset className="settings-fieldset">
        <legend>Model Selection (per task)</legend>
        {OLLAMA_TASKS.map((task) => (
          <OllamaTaskField
            key={task}
            task={task}
            value={state.ollamaModelAssignments[task] ?? "auto"}
            transport={transport}
          />
        ))}
      </fieldset>

      <label className="settings-field">
        <span className="settings-field-label">Validate and Pull Model</span>
        <input
          type="text"
          className="settings-select"
          list={OLLAMA_MODELS_DATALIST_ID}
          placeholder="Advanced model ID entry"
          value={draftPullModel}
          onChange={(event) => setDraftPullModel(event.target.value)}
        />
      </label>
      <div className="settings-button-row">
        <button
          type="button"
          className="settings-button settings-button-primary"
          disabled={draftPullModel.trim().length === 0 || state.ollamaPullStatus === "running"}
          onClick={() => transport.fireIntent("app-settings", "pullOllamaModel", [draftPullModel])}
        >
          {state.ollamaPullStatus === "running" ? "Validating..." : "Validate and Pull Model"}
        </button>
      </div>

      {state.ollamaNotice && (
        <p className="settings-update-status" data-level="error">
          {state.ollamaNotice}
        </p>
      )}
    </div>
  );
}

// Llama.cpp's runtime tunables (chat format, n_ctx, n_gpu_layers, n_threads)
// persist on every change - no separate Save step, unlike the model-path
// fields below. A plain value={state.llamaCpp*} binding (no local buffer)
// breaks multi-character typing: the fake test transport (and, over a real
// WS round trip, ordinary network latency) never echoes a change back
// before the NEXT keystroke fires, so the input keeps resetting to the
// stale last-confirmed value between keystrokes instead of accumulating
// what the user is typing. A small local draft, reset only when the
// confirmed value changes to something the draft doesn't already reflect
// (the same pattern OllamaTaskField/ApiProviderPage already use), fixes it.
//
// Adversarial-review finding, deliberately NOT further chased: this reset
// compares the incoming value only against the last value WE'VE SEEN, not
// against every edit we've SENT - so a same-session echo of an EARLIER
// keystroke landing after a NEWER one would still stomp the newer draft.
// A fully correct fix needs echo-cancellation (a pending-edit counter) or a
// backend-tracked version stamp; both add real state-machine complexity
// for a narrow window that requires sustained fast typing during a slow
// round trip on a loopback WS connection. This is the same class of
// already-accepted risk OllamaTaskField's own explicit-model-ID input has
// (no draft buffer at all there) - not a new regression, just not fully
// closed either.
function LlamaCppNumberField({
  label,
  value,
  min,
  max,
  step,
  placeholder,
  onCommit,
}: {
  label: string;
  value: number;
  min?: number;
  max?: number;
  step?: number;
  placeholder?: string;
  onCommit: (n: number) => void;
}) {
  const [draft, setDraft] = useState(String(value));
  const [lastValue, setLastValue] = useState(value);

  if (value !== lastValue) {
    setLastValue(value);
    setDraft(String(value));
  }

  return (
    <label className="settings-field">
      <span className="settings-field-label">{label}</span>
      <input
        type="number"
        className="settings-select"
        min={min}
        max={max}
        step={step}
        placeholder={placeholder}
        value={draft}
        onChange={(event) => {
          setDraft(event.target.value);
          const n = Number(event.target.value);
          if (!Number.isNaN(n) && event.target.value.trim() !== "") onCommit(n);
        }}
      />
    </label>
  );
}

function LlamaCppPage({ state, transport }: { state: AppSettingsState; transport: WsTransport }) {
  const [draftChatFormat, setDraftChatFormat] = useState(state.llamaCppChatFormat);
  const [lastChatFormat, setLastChatFormat] = useState(state.llamaCppChatFormat);

  if (state.llamaCppChatFormat !== lastChatFormat) {
    setLastChatFormat(state.llamaCppChatFormat);
    setDraftChatFormat(state.llamaCppChatFormat);
  }

  // Chat/title model path fields are STAGED server-side (backend/settings.py's
  // llama_staged_chat_path/llama_staged_title_path) - Browse/select updates
  // the draft immediately (visible via state), but nothing persists until
  // Save Settings, matching the API-provider page's own draft-then-commit
  // shape rather than Ollama's per-field immediate persist.
  const scannedChatValue = state.llamaCppScannedModels.includes(state.llamaCppChatModelPath)
    ? state.llamaCppChatModelPath
    : "";
  const scannedTitleValue = state.llamaCppScannedModels.includes(state.llamaCppTitleModelPath)
    ? state.llamaCppTitleModelPath
    : "";

  return (
    <div className="settings-general-page">
      <fieldset className="settings-fieldset">
        <legend>Reasoning Level</legend>
        {REASONING_LEVEL_OPTIONS.map((option) => (
          <label className="settings-checkbox-row" key={option.id}>
            <input
              type="radio"
              name="llama-cpp-reasoning-level"
              checked={state.llamaCppReasoningLevel === option.id}
              onChange={() => transport.fireIntent("app-settings", "setLlamaCppReasoningLevel", [option.id])}
            />
            {option.label}
          </label>
        ))}
      </fieldset>

      <p className="settings-update-status">
        Current Active GGUF: <strong>{state.llamaCppChatModelPath ? basename(state.llamaCppChatModelPath) : "No model selected"}</strong>
      </p>

      <div className="settings-button-row">
        <button
          type="button"
          className="settings-button"
          disabled={state.llamaCppScanStatus === "running"}
          onClick={() => transport.fireIntent("app-settings", "scanLlamaCppSystem", [])}
        >
          {state.llamaCppScanStatus === "running" ? "Scanning..." : "System Scan"}
        </button>
        <button
          type="button"
          className="settings-button"
          disabled={state.llamaCppScanStatus === "running"}
          onClick={() => transport.fireIntent("app-settings", "pickLlamaCppScanFolder", [])}
        >
          Scan Folder...
        </button>
      </div>
      <p className="settings-update-status">{state.llamaCppScanSummary}</p>

      <datalist id={LLAMA_CPP_MODELS_DATALIST_ID}>
        {state.llamaCppScannedModels.map((path) => (
          <option key={path} value={path} />
        ))}
      </datalist>

      {state.llamaCppScannedModels.length > 0 && (
        <div className="settings-field">
          <span className="settings-field-label">Scanned Chat Model</span>
          <CustomSelect
            ariaLabel="Scanned Chat Model"
            value={scannedChatValue}
            options={[
              { id: "", label: "Select a scanned model..." },
              ...state.llamaCppScannedModels.map((path) => ({ id: path, label: basename(path) })),
            ]}
            onChange={(path) => transport.fireIntent("app-settings", "setLlamaCppChatModelPath", [path])}
          />
        </div>
      )}

      <div className="settings-field">
        <span className="settings-field-label">Chat Model File</span>
        <span className="settings-update-status">{state.llamaCppChatModelPath || "No file selected"}</span>
        <button
          type="button"
          className="settings-button"
          onClick={() => transport.fireIntent("app-settings", "pickLlamaCppChatModelFile", [])}
        >
          Browse...
        </button>
      </div>

      {state.llamaCppScannedModels.length > 0 && (
        <div className="settings-field">
          <span className="settings-field-label">Scanned Naming Model</span>
          <CustomSelect
            ariaLabel="Scanned Naming Model"
            value={scannedTitleValue}
            options={[
              { id: "", label: "Select a scanned model..." },
              ...state.llamaCppScannedModels.map((path) => ({ id: path, label: basename(path) })),
            ]}
            onChange={(path) => transport.fireIntent("app-settings", "setLlamaCppTitleModelPath", [path])}
          />
        </div>
      )}

      <div className="settings-field">
        <span className="settings-field-label">Chat Naming File (optional)</span>
        <span className="settings-update-status">{state.llamaCppTitleModelPath || "Reusing the main chat model"}</span>
        <button
          type="button"
          className="settings-button"
          onClick={() => transport.fireIntent("app-settings", "pickLlamaCppTitleModelFile", [])}
        >
          Browse...
        </button>
      </div>

      <label className="settings-field">
        <span className="settings-field-label">Chat Format Override</span>
        <input
          type="text"
          className="settings-select"
          placeholder="Leave blank to let the GGUF metadata decide"
          value={draftChatFormat}
          onChange={(event) => {
            setDraftChatFormat(event.target.value);
            transport.fireIntent("app-settings", "setLlamaCppChatFormat", [event.target.value]);
          }}
        />
      </label>

      <LlamaCppNumberField
        label="Context Window"
        value={state.llamaCppNCtx}
        min={256}
        max={131072}
        step={256}
        onCommit={(n) => transport.fireIntent("app-settings", "setLlamaCppNCtx", [n])}
      />
      <LlamaCppNumberField
        label="GPU Layers"
        value={state.llamaCppNGpuLayers}
        min={-1}
        max={9999}
        onCommit={(n) => transport.fireIntent("app-settings", "setLlamaCppNGpuLayers", [n])}
      />
      <LlamaCppNumberField
        label="CPU Threads"
        value={state.llamaCppNThreads}
        min={0}
        max={256}
        placeholder="0 = Auto"
        onCommit={(n) => transport.fireIntent("app-settings", "setLlamaCppNThreads", [n])}
      />

      {state.llamaCppNotice && (
        <p className="settings-update-status" data-level="error">
          {state.llamaCppNotice}
        </p>
      )}

      <div className="settings-button-row">
        <button
          type="button"
          className="settings-button settings-button-primary"
          onClick={() => transport.fireIntent("app-settings", "saveLlamaCppSettings", [])}
        >
          Save Settings
        </button>
      </div>
    </div>
  );
}

export function SettingsDialog({ transport }: { transport: WsTransport }) {
  const [state, setState] = useState<AppSettingsState>(initialState);

  useEffect(() => {
    return transport.subscribe("app-settings", (payload) => {
      const validated = TOPIC_VALIDATORS["app-settings"](payload);
      if (validated.ok) setState(validated.value as AppSettingsState);
      else console.error("[app-settings] rejected snapshot:", validated.errors);
    });
  }, [transport]);

  const activeSection = (SECTIONS.find((s) => sectionKey(s) === state.activeSection) ?? "General") as Section;

  return (
    <Dialog name="settings" title="Settings" className="settings-dialog">
      {/* ADR-004 stage 4.4: persistent (visible regardless of which
          section tab is active, not a one-time toast) - a DPAPI failure
          means every API key/GitHub token this dialog saves from now on
          is written to disk in PLAINTEXT, a fact worth surfacing no
          matter which page a user happens to be on when it's true. Hidden
          entirely in the common case (secretsEncryptedAtRest is true).
          role="alert" (adversarial-review fix) matches every other warning/
          error banner in this codebase (BridgeErrorState.tsx, the 3
          node-view banner-error divs) - without it, the dialog's own focus
          trap moves focus straight to the rail buttons on open (this <p>
          isn't focusable), so screen-reader users could tab straight past
          this security-relevant text and never encounter it, and a later
          flip from encrypted to unencrypted while the dialog is already
          open would render with no assistive-tech announcement at all. */}
      {!state.secretsEncryptedAtRest && (
        <p className="settings-update-status settings-secrets-warning" data-level="warning" role="alert">
          API keys are stored unencrypted on this system (Windows DPAPI is unavailable or failing here).
        </p>
      )}
      <div className="settings-shell">
        <nav className="settings-rail" aria-label="Settings sections">
          {SECTIONS.map((section) => (
            <button
              key={section}
              type="button"
              className={"settings-rail-button" + (section === activeSection ? " active" : "")}
              aria-current={section === activeSection ? "page" : undefined}
              onClick={() => transport.fireIntent("app-settings", "setActiveSection", [sectionKey(section)])}
            >
              {section}
            </button>
          ))}
        </nav>
        <div className="settings-page" role="region" aria-label={activeSection}>
          {activeSection === "General" ? (
            <GeneralPage state={state} transport={transport} />
          ) : activeSection === "Integrations" ? (
            <IntegrationsPage state={state} transport={transport} />
          ) : activeSection === "API Endpoint" ? (
            <ApiProviderPage state={state} transport={transport} />
          ) : activeSection === "Ollama (Local)" ? (
            <OllamaPage state={state} transport={transport} />
          ) : activeSection === "Llama.cpp (Local)" ? (
            <LlamaCppPage state={state} transport={transport} />
          ) : (
            activeSection
          )}
        </div>
      </div>
    </Dialog>
  );
}
